### ISSUE TITLE
rpy2 does not support sparse matrices

### ISSUE THREAD

**Issue by LuckyMD** [theislab/single-cell-tutorial#1]
A warning should be added that R method integration relies on `rpy2`, which only supports dense matrices.

**Comment by LuckyMD** [comment]
Added a note in the README in #d29cbfd7083bf8c4a5a8b1d5e796f0bd62f640bb

**Comment by jphe** [comment]
> Added a note in the README in [d29cbfd](https://github.com/theislab/single-cell-tutorial/commit/d29cbfd7083bf8c4a5a8b1d5e796f0bd62f640bb)

Hi,

Thanks for your reply, I met another problem for the batch correction "**
data = pd.DataFrame(adata.X)
batch = pd.Series(adata.obs['sample'])
batch = batch.reset_index()
data_cor = c.combat(data=data.T, batch=batch['sample'])**", 
it reports "**TypeError: data type not understood**", I have tried **"np.dtype(data)"**, also the same error, seems numpy can not recognize the pandas dataframe type?  Can you help me? Thanks.

**Comment by LuckyMD** [comment]
Hi,

This seems to be a different error that is not related to your previous issue. It would be good to make a separate issue for this. I will try to address this elsewhere.
