### ISSUE TITLE
Error when assigning variable names and gene id columns

### ISSUE THREAD

**Issue by PattF** [theislab/single-cell-tutorial#10]
Hi,
Great tutorial! I'm trying to use it on a dataset comprised of 2 samples that I've concatenated following the initial steps described in your tutorial.
My initial issue comes up when running line 6 "#Assign variable names and gene id columns
adata.var_names = [g.split("_")[1] for g in adata.var_names]
adata.var['gene_id'] = [g.split("_")[1] for g in adata.var['gene_id']]" where I get the following error:

IndexError                                Traceback (most recent call last)
<ipython-input-6-9be4081fa0c6> in <module>
      1 #Assign variable names and gene id columns
----> 2 adata.var_names = [g.split("_")[1] for g in adata.var_names]
      3 adata.var['gene_id'] = [g.split("_")[1] for g in adata.var['gene_id']]

<ipython-input-6-9be4081fa0c6> in <listcomp>(.0)
      1 #Assign variable names and gene id columns
----> 2 adata.var_names = [g.split("_")[1] for g in adata.var_names]
      3 adata.var['gene_id'] = [g.split("_")[1] for g in adata.var['gene_id']]

IndexError: list index out of range

If I change the [1] to [0] I can continue with the subsequent script lines although I get "Variable names are not unique. To make them unique, call `.var_names_make_unique`." throughout. I'm not entirely sure what the [1] variable represents, any help would be appreciated understanding the error.

---
An additional error I get is when running line 31 (after changing [1] to [0] on line 6) is when attempting to do cell cycle scoring. I get the following error: 

AxisError                                 Traceback (most recent call last)
<ipython-input-32-b60d52295300> in <module>
     12 g2m_genes_mm_ens = adata.var_names[np.in1d(adata.var_names, g2m_genes_mm)]
     13 
---> 14 sc.tl.score_genes_cell_cycle(adata, s_genes=s_genes_mm_ens, g2m_genes=g2m_genes_mm_ens)

~\Anaconda3\lib\site-packages\scanpy\tools\_score_genes.py in score_genes_cell_cycle(adata, s_genes, g2m_genes, copy, **kwargs)
    185     ctrl_size = min(len(s_genes), len(g2m_genes))
    186     # add s-score
--> 187     score_genes(adata, gene_list=s_genes, score_name='S_score', ctrl_size=ctrl_size, **kwargs)
    188     # add g2m-score
    189     score_genes(adata, gene_list=g2m_genes, score_name='G2M_score', ctrl_size=ctrl_size, **kwargs)

~\Anaconda3\lib\site-packages\scanpy\tools\_score_genes.py in score_genes(adata, gene_list, ctrl_size, gene_pool, n_bins, score_name, random_state, copy, use_raw)
    114     X_control = _adata[:, control_genes].X
    115     if issparse(X_control): X_control = X_control.toarray()
--> 116     X_control = np.nanmean(X_control, axis=1)
    117 
    118     if len(gene_list) == 0:

~\Anaconda3\lib\site-packages\numpy\lib\nanfunctions.py in nanmean(a, axis, dtype, out, keepdims)
    861         raise TypeError("If a is inexact, then out must be inexact")
    862 
--> 863     cnt = np.sum(~mask, axis=axis, dtype=np.intp, keepdims=keepdims)
    864     tot = np.sum(arr, axis=axis, dtype=dtype, out=out, keepdims=keepdims)
    865     avg = _divide_by_count(tot, cnt, out=out)

~\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py in sum(a, axis, dtype, out, keepdims, initial)
   1928 
   1929     return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
-> 1930                           initial=initial)
   1931 
   1932 

~\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     77             # support a dtype.
     78             if dtype is not None:
---> 79                 return reduction(axis=axis, dtype=dtype, out=out, **passkwargs)
     80             else:
     81                 return reduction(axis=axis, out=out, **passkwargs)

~\Anaconda3\lib\site-packages\numpy\core\_methods.py in _sum(a, axis, dtype, out, keepdims, initial)
     34 def _sum(a, axis=None, dtype=None, out=None, keepdims=False,
     35          initial=_NoValue):
---> 36     return umr_sum(a, axis, dtype, out, keepdims, initial)
     37 
     38 def _prod(a, axis=None, dtype=None, out=None, keepdims=False,

AxisError: axis 1 is out of bounds for array of dimension 1

Any help would be greatly appreciated understanding these errors, thanks!

Currently running scanpy==1.4 anndata==0.6.18 numpy==1.15.4 scipy==1.1.0 pandas==0.23.4 scikit-learn==0.20.0 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1

**Comment by LuckyMD** [comment]
Hi @PattF, 
Thanks for the kind words. 

Reading in the data is a dataset specific task, that will differ slightly depending between data formats. There are a lot of functions within scanpy to read in data stored in different formats. You can find the functions [here](https://scanpy.readthedocs.io/en/latest/api/index.html#reading).

In the tutorial datasets the variable names are stored as MGI gene symbol preceded by `mm10_`. For example, the output for `adata.var_names[:10]` is the following if run before line [6].
```
Index(['mm10_Xkr4', 'mm10_Gm1992', 'mm10_Gm37381', 'mm10_Rp1', 'mm10_Rp1-1',
       'mm10_Sox17', 'mm10_Gm37323', 'mm10_Mrpl15', 'mm10_Lypla1',
       'mm10_Gm37988'],
      dtype='object')
```

I just wanted to get rid of the `mm10_` parts in the gene names. I will write a note about this in the script to make this clear.

By the way, a new version of the case study will be uploaded this week which works for pandas 0.24 and has a better integration with R... along with some nice additions. This version will still be available, but probably in a `old_versions` folder or something like that.

Best,

Malte
