### ISSUE TITLE
How can we change the plot shape (not only using dot) of UMAP in Scanpy?

### ISSUE THREAD

**Issue by melancholy12** [theislab/single-cell-tutorial#101]
Now we only plot the UMAP in the shape "●". Can we also plot the UMAP by using “▲” or “■”？

**Comment by Zethson** [comment]
You can pass a marker as kwarg to https://scanpy.readthedocs.io/en/stable/generated/scanpy.pl.umap.html which gets passed to the marker argument of https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html

**Comment by melancholy12** [comment]
@Zethson  I am a beginner for snRNA sequencing analysis.
Could you also share me simple code for this? Because I never use **kwarg function before.
Thanks very much!
