### ISSUE TITLE
Scale before calculating gene score, and after regressing out cell cycle ?

### ISSUE THREAD

**Issue by carmensandoval** [theislab/single-cell-tutorial#103]
#35 #73 

Hello,

According to the [cell cycle notebook](https://nbviewer.org/github/theislab/scanpy_usage/blob/master/180209_cell_cycle/cell_cycle.ipynb), one should scale `adata` prior to running `score_genes_cell_cycle`.

However, there is another scaling performed after regressing out cell cycle. Is this the correct way to do it? Is the second call to `sc.pp.scale` just going back to the the log-normed data? Or is it scaling an already scaled matrix?

Thanks

```
sc.pp.filter_genes(adata, min_cells=50)
sc.pp.normalize_total(adata, target_sum=1e4)

adata.raw = adata

sc.pp.log1p(adata)
sc.pp.scale(adata)
sc.tl.score_genes_cell_cycle(adata, s_genes = s_genes, g2m_genes= g2m_genes)

sc.pp.highly_variable_genes(adata)
adata = adata[:, adata.var.highly_variable]

sc.pp.regress_out(adata, ['S_score', 'G2M_score'])
sc.pp.scale(adata)
```

**Comment by LuckyMD** [comment]
Hi!

The tutorial you are referring to is pretty old and does indeed scale twice. That is one of the reasons I wrote this current best-practices tutorial for single-cell analysis. I would normally not scale the data at all for calling cell cycle stages as is also shown in the tutorial in this github repo.

**Comment by carmensandoval** [comment]
Awesome - thanks for your response!

**Comment by alifarhat40** [comment]
> best-practices tutorial for single-cell analysis

Hi. Where can I find this tutorial? @LuckyMD
