### ISSUE TITLE
List of package versions for the latest version of the notebook

### ISSUE THREAD

**Issue by davidecarlson** [theislab/single-cell-tutorial#104]
Hi All,

I've been trying to work through [the latest version](https://github.com/theislab/single-cell-tutorial/tree/master/latest_notebook) of the single cell tutorial notebook, but I inevitably run into various errors, which I believe are likely caused by having the wrong versions of various packages.

Would it be possible to get a list of _all_ the software versions that were used to successfully run the above-referenced notebook?  Similar to the sc_tutorial_environment.yml file, but with the version numbers for each package.

For example, if someone who is able to run the whole notebook successfully from start to finish could run and attach the output of `conda env export`, that would be super helpful!

Thank you!
Dave

**Comment by davidecarlson** [comment]
Since the R packages would not necessarily be installed by conda, having a list of the specific R package versions would be helpful as well.  For example (stolen from [here](https://www.r-bloggers.com/2015/06/list-of-user-installed-r-packages-and-their-versions/)):

```
ip <- as.data.frame(installed.packages()[,c(1,3:4)])
rownames(ip) <- NULL
ip <- ip[is.na(ip$Priority),1:2,drop=FALSE]
print(ip, row.names=FALSE)
```

Thanks!

**Comment by LuckyMD** [comment]
Hi @davidecarlson,

I'm currently travelling, so not able to do the above. However, you can check out the [docker image](https://hub.docker.com/r/leanderd/single-cell-analysis) we have generated and run that to export the versions of each package.

**Comment by davidecarlson** [comment]
Thanks.  I was able to get export the package versions from the docker image, and will try to set up my environment based on that.
