### ISSUE TITLE
concatenate to main adata object

### ISSUE THREAD

**Issue by Yuling-Zhao** [theislab/single-cell-tutorial#107]
Dear all,

Thanks for the beautiful case study scripts!

I am very new to scRNA analysis and also a new coding learner. I may ask a too fundamental question, but I don't know where to find the solution.

In the chunk of #loop to load rest of data sets, the concatenate doesn't work.
adata = adata.concatenate(adata_tmp, batch_key='sample_id')
ValueError: cannot reindex from a duplicate axis

Can you help me with this?

Thanks for your help in advance!

Best,
Yuling

**Comment by pakiessling** [comment]
Add `adata.var_names_make_unique()` to the end of cell 5.

See also #82
