### ISSUE TITLE
AttributeError: module 'pertpy.tools' has no attribute 'Milopy'

### ISSUE THREAD

**Issue by nroak** [theislab/single-cell-tutorial#112]
### Report

I installed the latest version of pertpy from GitHub pull but getting an error at the step below:

```
> milo = pt.tl.Milopy()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[47], line 1
----> 1 milo = pt.tl.Milopy()

AttributeError: module 'pertpy.tools' has no attribute 'Milopy'

```
However this works- 
`> milo = pt.tl.Milo()`

The tutorial needs to be updated.

**Comment by LuckyMD** [comment]
This is the wrong repo to report issues for pertpy.

**Comment by nroak** [comment]
My comment was regarding updating the tutorial to reflect current command that works.
