### ISSUE TITLE
Converting between sparse and dense matrices

### ISSUE THREAD

**Issue by PattF** [theislab/single-cell-tutorial#12]
Hi Malte,

Question about sparse and dense matrices. I understand we need to work with dense matrices in order to use rpy2. Is there a way to convert back to a sparse matrix (at the end of the tutorial?) if needed for other functions downstream? 
My understanding of how dense vs sparse formats are handled is limited. 

Not sure I understand it, but do most of the scanpy notebooks run off sparse matrices?
I tried running `bdata = sp.sparse.csr_matrix(adata)` to convert to a sparse matrix but got an error of ValueError: unrecognized csr_matrix constructor usage.

Previously when working off the scanpy notebooks I used to run a function to generate a gene regulatory network based off a list of provided transcripts. I get an error when trying to run that function in the current dense format after following the tutorial and I'm wondering if its to do with dense/sparse matrices. Happy to take this offline if you'd like more detail.

Thanks!

**Comment by LuckyMD** [comment]
Hi @PattF, 

So there are a couple of issues with using sparse matrices with this tutorial. `rpy2` is one of them... another is batch correction. While `rpy2` (or now `anndata2ri` in the newest version) cannot accept sparse matrices, ComBat (and all other batch correction/data integration tools I am aware of) will output a matrix that is no longer dominated by 0 values. You can of course run ComBat in such a way that either zeros are retained (setting all pre-combat 0s, to 0 after combat), or that all negative values are cast to 0... but we've not done that in the case study. It's also arguable whether this is not just a distortion of the expression values in a biased way to benefit computation efficiency (i.e., the zeros are artificial and they should not be there).

That being said, you should be able to turn your matrix back into a sparse format by running something like this: `adata.X = sp.sparse.csr_matrix(adata.X)`. But the sparse representation may not longer be a good idea with the matrices that you do this to.

To be honest, I can't see why a downstream method would only work for sparse matrix representations. This is just a convenient way to represent the data using less memory to load it (if there are a lot of zeros), but the data is no different in sparse or dense representation.

I'm not entirely sure what you mean by a "list of provided transcripts". A sparse matrix would not constitute that input format either. You can obtain a list of transcripts from `adata.var_names`.

Hope that helps.

**Comment by PattF** [comment]
Thanks for the explanation, makes more sense now!
I was just assuming it might have to do with sparse vs dense matrices as the function I'm trying to run contains a section with `scipy.sparse.csr_matrix.` Happy to take this offline if you're interest to see what I mean, I fear posting it all here is out of scope for the tutorial.
Thanks again.

**Comment by LuckyMD** [comment]
Maybe the method expects a count matrix? It's probably best to take this discussion elsewhere.
