### ISSUE TITLE
Issue with rgl package when trying to load slingshot

### ISSUE THREAD

**Issue by brennerUT** [theislab/single-cell-tutorial#13]
Everything is working for me except for the slingshot package. When I try to load it via rpy2, I get the error shown below. The version of R that I have installed is 3.5.1, if that helps at all.

```
R[write to console]: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/stor/home/ericb123/anaconda3/envs/sc-tutorial/lib/R/library/rgl/libs/rgl.so':
  dlopen: cannot load any more object with static TLS

R[write to console]: In addition: 
R[write to console]: Warning message:

R[write to console]: replacing previous import ‘SingleCellExperiment::weights’ by ‘stats::weights’ when loading ‘slingshot’ 

R[write to console]: Error: package or namespace load failed for ‘slingshot’:
 .onLoad failed in loadNamespace() for 'rgl', details:
  call: NULL
  error:        Loading rgl's DLL failed. 


Error: package or namespace load failed for ‘slingshot’:
 .onLoad failed in loadNamespace() for 'rgl', details:
  call: NULL
  error:        Loading rgl's DLL failed.
```

**Comment by LuckyMD** [comment]
Hi,

This looks like an issue with your `rgl` library. It will be quite difficult for me to debug this, as it depends on your setup, which I cannot easily recreate. Googling brought be here (in case you are running on MacOS):
https://stackoverflow.com/questions/9878693/error-in-loading-rgl-package-with-mac-os-x

Which version of the case study are you using for this? Are you using `anndata2ri` or the older version with only `rpy2`?

**Comment by brennerUT** [comment]
Ah, I was worried it would be an issue with my personal setup. I'm running this on Ubuntu on a remote computer I'm accessing from my Windows laptop via MobaXterm.

I'm using the newest notebook from this repository, with anndata2ri.

**Comment by LuckyMD** [comment]
I'm afraid I have absolutely no experience with Windows and MobaXterm, so I can't really help you with this. 

This is probably something you'll have to do yourself. If you don't get much further, you could also try the slingshot github repo. The Slingshot developer is usually very quick to respond and might be able to help you if you post an issue there.

**Comment by mvonpapen** [comment]
Hey @brennerUT,
did you solve your problem? I run into the same rgl error when I try to install slingshot on a jupyter/minimal docker image with R version 3.6 from conda. Would be very interested to hear how you proceeded.

**Comment by LuckyMD** [comment]
Hey!

So if you're running via a linux image, it could just be that you have to link your `gsl` libraries from R. Have you tried to follow  the README for this?

**Comment by mvonpapen** [comment]
FYI, I just solved the problem for my `jupyter/minimal-notebook` docker image. Apparently, an OpenGL package was missing. Running
```
apt-get update
apt-get install libgl1-mesa-glx
```
as root before the installation of slingshot solved the issue for me. I don't know if this is the best of all fixes, but it worked for me.

**Comment by LuckyMD** [comment]
Hmm... this might have to be added to our `requirements.txt` for conda. Can you get OpenGL via conda as well?

Were you using miniconda or anaconda?
