### ISSUE TITLE
sc.tl.marker_gene_overlap error

### ISSUE THREAD

**Issue by JuHey** [theislab/single-cell-tutorial#14]
Hi LuckyMD,

I was exploring the new sc tutorial and am having an issue with the marker_gene_overlap function. The error is: module 'scanpy.tools' has no attribute 'marker_gene_overlap'. And when I look at the scanpy API, it is not listed under tools. I tried updating scanpy but that did not change. How can I implement marker_gene_overlap?

Cheers,

Jurgen

**Comment by LuckyMD** [comment]
Hi Jurgen,

the `sc.tl.marker_gene_overlap()` function is available on the current master branch of the scanpy repo. You will need to use that branch. This will be released in `scanpy 1.4.1`. Which version are you using?

Best,

Malte

**Comment by JuHey** [comment]
Hi Malte,

I am using `scanpy 1.4`. I will use the branch you indicated. I think it is an excellent addition to scanpy!!!

Best,

Jurgen

**Comment by LuckyMD** [comment]
I'm glad you like it. Also, there is a discussion about extending the function to looking at differential densities... so that might happen at some point as well.

By the way... there are README files with the notebooks that should say which versions of the packages the notebooks require.
