### ISSUE TITLE
Unable to deploy the .yml - Docker enhancement request

### ISSUE THREAD

**Issue by marshelma** [theislab/single-cell-tutorial#17]
Creating the environment with the yml file provided generate error:

WARNING: The conda.compat module is deprecated and will be removed in a future release.
WARNING: The conda.compat module is deprecated and will be removed in a future release.

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/xma/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1003, in __call__
        return func(*args, **kwargs)
      File "/home/xma/anaconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 73, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/xma/anaconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 77, in execute
        directory=os.getcwd())
      File "/home/xma/anaconda3/lib/python3.7/site-packages/conda_env/specs/__init__.py", line 40, in detect
        if spec.can_handle():
      File "/home/xma/anaconda3/lib/python3.7/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/home/xma/anaconda3/lib/python3.7/site-packages/conda_env/env.py", line 143, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/home/xma/anaconda3/lib/python3.7/site-packages/conda_env/env.py", line 128, in from_yaml
        data = yaml_load_standard(yamlstr)
      File "/home/xma/anaconda3/lib/python3.7/site-packages/conda/common/serialize.py", line 76, in yaml_load_standard
        return yaml.load(string, Loader=yaml.Loader, version="1.2")
      File "/home/xma/anaconda3/lib/python3.7/site-packages/ruamel_yaml/main.py", line 640, in load
        return loader._constructor.get_single_data()  # type: ignore
      File "/home/xma/anaconda3/lib/python3.7/site-packages/ruamel_yaml/constructor.py", line 102, in get_single_data
        node = self.composer.get_single_node()
      File "/home/xma/anaconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 75, in get_single_node
        document = self.compose_document()
      File "/home/xma/anaconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 99, in compose_document
        self.parser.get_event()
      File "/home/xma/anaconda3/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 166, in get_event
        self.current_event = self.state()
      File "/home/xma/anaconda3/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 244, in parse_document_end
        token = self.scanner.peek_token()
      File "/home/xma/anaconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 173, in peek_token
        self.fetch_more_tokens()
      File "/home/xma/anaconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 273, in fetch_more_tokens
        return self.fetch_value()
      File "/home/xma/anaconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 626, in fetch_value
        self.reader.get_mark())
    ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
      in "<unicode string>", line 32, column 187:
         ...  in single-cell RNA-seq analysis: a tutorial&quot;  - theislab/s ... 
                                             ^ (line: 32)

`$ /home/xma/anaconda3/bin/conda-env create -f /home/xma/Downloads/sc_tutorial_environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/xma/anaconda3/bin/conda
             CONDA_PREFIX=/home/xma/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
               CONDA_ROOT=/home/xma/anaconda3
              CONDA_SHLVL=1
                     PATH=/home/xma/anaconda3/bin:/home/xma/anaconda3/condabin:/home/xma/anacond
                          a3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/u
                          sr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : base
    active env location : /home/xma/anaconda3
            shell level : 1
       user config file : /home/xma/.condarc
 populated config files : /home/xma/.condarc
          conda version : 4.6.11
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : /home/xma/anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/xma/anaconda3/pkgs
                          /home/xma/.conda/pkgs
       envs directories : /home/xma/.conda/envs
                          /home/xma/anaconda3/envs
               platform : linux-64
             user-agent : conda/4.6.11 requests/2.21.0 CPython/3.7.3 Linux/4.18.0-20-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

**Comment by LuckyMD** [comment]
Hi,

I assume you were running the command:
`conda env create -f sc_tutorial_environment.yml`

I just ran this and cannot recreate the issue. It runs fine for me on Fedora 28. I can try on Fedora 25 as well, but I doubt it will be any different. What system are you running this on?

**Comment by marshelma** [comment]
> Hi,
> 
> I assume you were running the command:
> `conda env create -f sc_tutorial_environment.yml`
> 
> I just ran this and cannot recreate the issue. It runs fine for me on Fedora 28. I can try on Fedora 25 as well, but I doubt it will be any different. What system are you running this on?

Hi,

I'm on a Ubuntu 18.04 system. The conda version is 4.6.11 and anaconda release is 2019.3, py version is 3.7.0.

**Comment by LuckyMD** [comment]
I'm a little bit confused how your error includes
```
in "<unicode string>", line 32, column 187:
     ...  in single-cell RNA-seq analysis: a tutorial&quot;  - theislab/s ... 
                                         ^ (line: 32)
```
This line includes the title of the paper, which is not in the `sc_tutorial_environment.yml` file... so conda shouldn't know about it. Have you changed the yml file at all?

Testing this on a docker container that contains ubuntu 18.04 will take me a bit of time...

**Comment by marshelma** [comment]
> I'm a little bit confused how your error includes
> 
> ```
> in "<unicode string>", line 32, column 187:
>      ...  in single-cell RNA-seq analysis: a tutorial&quot;  - theislab/s ... 
>                                          ^ (line: 32)
> ```
> 
> This line includes the title of the paper, which is not in the `sc_tutorial_environment.yml` file... so conda shouldn't know about it. Have you changed the yml file at all?
> 
> Testing this on a docker container that contains ubuntu 18.04 will take me a bit of time...

I directly download it from github, did not change anything in it. I have manually installed all the packages actually... However, it might be a good idea if you can release a docker image then everyone can load it from docker.

Best.

**Comment by LuckyMD** [comment]
Agreed. This is on my to-do list.

Thanks for the feedback.

**Comment by rmenafra** [comment]
Hi,
if you download the yml directly from github it doesn't save it correctly (at least this was my case). If you then try to visualize its content it looks like a html page...
If you first open it and then just save the text content it works fine.
I agree that the docker container would be of great help!
I didn't succeed in installing all the libraries on my Mac, I'm trying now on linux.
Thanks for this resource!

**Comment by LuckyMD** [comment]
Thanks for the update on this. conda hasn't been playing well with packages installed via R on my mac either. That's why there are separate instructions for installing on mac.

**Comment by rmenafra** [comment]
Hi, 
indeed I followed the separate instruction for my Mac, but still, Slingshot it's only available for R version 3.6 (therefore dependency for R should at least be 3.6). However when I try to install R 3.6 in my base conda environment it says:
"UnsatisfiableError: The following specifications were found to be incompatible with each other:
  - pkgs/main/osx-64::libopenblas==0.3.6=hdc02c5d_0
  - r=3.6.0 
So I didn't exactly know how to proceed with this.
If you have any feedback it would be appreciated.

Concerning the installation on Linux, I'm using a shared cluster with  Ubuntu 14.04.6 LTS.
Also there Slingshot call from the notebook fails due to:
"Error: package or namespace load failed for ‘slingshot’:
 .onLoad failed in loadNamespace() for 'rgl', details:
  call: NULL
  error: 	Loading rgl's DLL failed. "
So I proceeded without using Slingshot for now because I cannot really install this R package in my environment since require rgl and gl.h libraries from the server I believe....(I don't have the exact error right now but I can recreate it eventually).
Thanks
Roberta

**Comment by LuckyMD** [comment]
Hi again,

There are a few issues here:
1. Slingshot for R 3.5. This should definitely be available via bioconductor 3.8 (I am using it). You can always get slingshot from github and edit the `DESCRIPTION` file as described for R 3.4.3 in the README. Or use a previous github release. I will at some point attempt to update everything to a newer version of R, but this is often quite a time-taking endeavor unfortunately. 

On another note, I have stopped using conda with Mac as I felt it creates more issues than it solves. I would try using system python and R. You can always create pip environments.

2. For the linux installation: This sounds to me as though R can't find your gsl library. Have you set the CFLAGS/LDFLAGS command to allow for this? Installing on the server is always difficult though. I would try to pay attention that you don't have the server R library in your `.libPaths()` while installing (to make sure you get the newest version of all dependencies), and then see if that helps. On the other hand.. Ubuntu 14.04 is quite old...

I see a docker image would solve a lot of these issues though... that's def the next priority.

**Comment by LuckyMD** [comment]
Also, check out #13

**Comment by LuckyMD** [comment]
docker image available now, and is in the process of being updated.
