### ISSUE TITLE
Concatenate files error

### ISSUE THREAD

**Issue by davidepisu** [theislab/single-cell-tutorial#18]
I'm following the notebook but I'm getting an error in concatenating the files:

```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-b1c46f8469f7> in <module>
     28 
     29     # Concatenate to main adata object
---> 30     adata = adata.concatenate(adata_tmp)
     31     adata.var['gene_id'] = adata.var['gene_id-1']
     32     adata.var.drop(columns = ['gene_id-1', 'gene_id-0'], inplace=True)

~/anaconda3/envs/sc-tutorial/lib/python3.7/site-packages/anndata/base.py in concatenate(self, join, batch_key, batch_categories, index_unique, *adatas)
   2018             # var
   2019             for c in ad.var.columns:
-> 2020                 new_c = c + (index_unique if index_unique is not None else '-') + categories[i]
   2021                 var.loc[vars_intersect, new_c] = ad.var.loc[vars_intersect, c]
   2022 

TypeError: unsupported operand type(s) for +: 'int' and `'str'`
```

I'm using this parameters:

```py
#Data files
sample_strings = ['bystander', 'uninfected', 'infected']
sample_id_strings = ['1', '2', '3']
file_base = '/home/ec2-user/LSHIV/LSHIV8'
exp_string = '_Regional_'
data_file_end = '_matrix.mtx'
barcode_file_end = '_barcodes.tsv'
gene_file_end = '_genes.tsv'
cc_genes_file = '~/pipeline/Macosko_cell_cycle_genes.txt'`
```

**Comment by davidepisu** [comment]
Also, my dataset are from Chromium V3 chemistry.... 

I don't honestly see where is trying to concatenate a string + integer and giving the error.

Wonder what this line of code actually does:
 new_c = c + (index_unique if index_unique is not None else '-') + categories[i]

**Comment by LuckyMD** [comment]
Hi,

I guess you are running the script on your own dataset. Is that correct? As I ran this yesterday with the case study data and I had no trouble.

Otherwise this looks like a scanpy error to me and I would report it there. My guess is that you have integer indices in `adata.obs_names` or `adata.var_names`. Changing this should solve the issue.

**Comment by ccruizm** [comment]
Hello,

I am having exactly the same issue. I do not see any integer indexes in the variables you mention @LuckyMD. I am also using V3 chemistry. The cell barcodes have an additional ‘-1’ and thought this might be the problem but removing it didn’t change anything. Any updates about this problem @davidepisu? Thanks in advance!

**Comment by LuckyMD** [comment]
Is this on your own dataset? If yes, then I would run it by scanpy. Also, it would be good to have a minimal reproducible example so I (or someone else) can recreate the issue.

**Comment by ccruizm** [comment]
sorry for the delayed reply. Yes, it is in my own dataset. this is the error message

`TypeError                                 Traceback (most recent call last)
<ipython-input-11-01aaadebece1> in <module>
     30 
     31     # Concatenate to main adata object
---> 32     adata = adata.concatenate(adata_tmp, batch_key='sample_id')
     33     adata.var['gene_id'] = adata.var['gene_id-1']
     34     adata.var.drop(columns = ['gene_id-1', 'gene_id-0'], inplace=True)

~/miniconda3/envs/sc-tutorial/lib/python3.7/site-packages/anndata/base.py in concatenate(self, join, batch_key, batch_categories, index_unique, *adatas)
   2018             # var
   2019             for c in ad.var.columns:
-> 2020                 new_c = c + (index_unique if index_unique is not None else '-') + categories[i]
   2021                 var.loc[vars_intersect, new_c] = ad.var.loc[vars_intersect, c]
   2022 

TypeError: unsupported operand type(s) for +: 'int' and 'str'`

This happens in the first loop to load all the datasets. Then, I decided to run only one dataset and see what happened. The same error (unsupported operand type(s) for +: 'int' and 'str') showed up when I plot the data quality summary plots:

`p1 = sc.pl.scatter(adata, 'n_counts', 'n_genes', color='mt_frac')
p2 = sc.pl.scatter(adata[adata.obs['n_counts']<10000], 'n_counts', 'n_genes', color='mt_frac')`

and here

`adata = adata[adata.obs['mt_frac'] < 0.2]
print('Number of cells after MT filter: {:d}'.format(adata.n_obs))

sc.pp.filter_cells(adata, min_genes = 700)
print('Number of cells after gene filter: {:d}'.format(adata.n_obs))`

Please find attached an example of the data I am working on. Thanks in advance

[barcodes.tsv.gz](https://github.com/theislab/single-cell-tutorial/files/3372384/barcodes.tsv.gz)
[features.tsv.gz](https://github.com/theislab/single-cell-tutorial/files/3372385/features.tsv.gz)
[matrix.mtx.gz](https://github.com/theislab/single-cell-tutorial/files/3372386/matrix.mtx.gz)

**Comment by mvonpapen** [comment]
Hi, I just resolved this error, which happened for me with scanpy version 1.4.4. The root cause is a change in the scanpy function adata.concatenate. You need to use scanpy version 1.4.3.

**Comment by LuckyMD** [comment]
Thanks for the reply @mvonpapen. Once I have some bandwidth I'll take a look at the change. There shouldn't have been a backwards-breaking change in `adata.concatenate()` in the  update as far as I'm aware.

**Comment by LuckyMD** [comment]
@Koncopd could it be that your commit https://github.com/theislab/anndata/commit/b768fd029af4fa106dba5635f4d692496e6a7cf7 for removing `var` column duplicates caused this?

**Comment by Koncopd** [comment]
I have no ideas how it can cause this. It seems from the error text that a column of `var` is integer for some reason. I will check this.

**Comment by LuckyMD** [comment]
Thanks!

Just to check: @ccruizm and @davidepisu, have you loaded in 10x dataset using the `sc.read()` function rather than `sc.read_10x()`? In that case the second var column tends to be an integer column name that would cause this error.

**Comment by mvonpapen** [comment]
> Thanks for the reply @mvonpapen. Once I have some bandwidth I'll take a look at the change. There shouldn't have been a backwards-breaking change in `adata.concatenate()` in the update as far as I'm aware.
> 
> Are you sure this is related to scanpy 1.4.3 and not anndata < 0.6.22?

You are correct, @LuckyMD! In the working version I had
  `scanpy==1.4.3 anndata==0.6.21`
compared to non-working version with
`  scanpy==1.4.4 anndata==0.6.22.post1`

I just ran a
`pip install anndata==0.6.21`
on the non-working version and tada! Error's gone.

For completeness: `sc.logging.print_versions()` gives:
`scanpy==1.4.4 anndata==0.6.21 umap==0.3.9 numpy==1.16.4 scipy==1.3.0 pandas==0.25.0 scikit-learn==0.21.2 statsmodels==0.10.1 python-igraph==0.7.1 louvain==0.6.1`

**Comment by LuckyMD** [comment]
Thanks @mvonpapen ! So it was a recent `anndata` update then. And you don't have any integer column names in your dataset when you concatenate? 

I hope this helps checking whether this was due to the recent removal of var column duplicates, @Koncopd

**Comment by mvonpapen** [comment]
> Thanks @mvonpapen ! So it was a recent anndata update then. And you don't have any integer column names in your dataset when you concatenate?

I'm using the Haber2019 dataset. Here, all columns are named "gene_id" and become "gene_id-0" and "gene_id-1" after concatenation.

**Comment by Koncopd** [comment]
@LuckyMD 
I ran the notebook and it works fine for me without any errors during concatenation. So i can't recreate the error with the Haber dataset.

However these strings should be removed fron the loading part
```
adata.var['gene_id'] = adata.var['gene_id-1']
adata.var.drop(columns = ['gene_id-1', 'gene_id-0'], inplace=True)
```
as there are no `gene_id-1` after concatenation anymore.

**Comment by LuckyMD** [comment]
Hi @Koncopd,

Thanks for that! I'm aware of the duplicate removal. I haven't updated the notebook to only work with the newest `anndata` and `scanpy` yet. That's on the to-do list though.

@ccruizm and @davidepisu, could you update `scanpy` and `anndata` to see if your issue is resolved? Or check for integer column names?

Best,

Malte

**Comment by ccruizm** [comment]
Hi there,

Updating `scanpy` and `anndata` and removing those two lines of code that @Koncopd suggested before, has solved the issue for me.

Thanks for the help!

**Comment by kyrenya** [comment]
Hi there,

I'm trying to run latest notebook, and when I get to the code chunk #loop to load rest of data sets, the kernel restarts automatically everytime. 
I'm trying to run it on linux, and 
these are my sc versions. 

I've already commented out the two lines that shouldnt be there with recent anndata versions, as explained here.

scanpy==1.4.5.1 anndata==0.7.1 umap==0.3.10 numpy==1.18.1 scipy==1.4.1 pandas==1.0.1 scikit-learn==0.22.1 statsmodels==0.11.0 python-igraph==0.8.0 louvain==0.6.1


Thanks in advance for your help!

**Comment by LuckyMD** [comment]
Hi @kyrenya,

Could this have to do with the memory use on your system? Are you loading the example data or your own datasets?

Just as an aside: the notebook is still not updated for the newest versions of `scanpy` and `anndata`. I'm also unsure of `pandas >=1.0.0`.

**Comment by kyrenya** [comment]
Thank you very much for your fast answer. 

 I ,ve also tried downgrading the versions of scanpy anndata and pandas to the ones mentioned here, and the problem persisted. 
On the other hand, I,m gonna try to run it in a server with better specs than my PC and I will let you know if we can discard the memory issues or not. 

Thanks a lot for your attention.

**Comment by minhtran1309** [comment]
I can confirm the situation with `anndata==0.6.22.post1` it happens when I install `anndata2ri` from `conda install -c bioconda anndata2ri` and it comes with that error, my data is 10X data and the solution that is mentioned above by downgrading `anndata` wouldn't resolve my problem. 
So I came up with another trick
`genes_tmp.rename(columns={0:'gene_id', 1:'gene_symbol', 2: 'gene_expression'}, inplace=True)`
Hope it helps for others

**Comment by minhtran1309** [comment]
> Thank you very much for your fast answer.
> 
> I ,ve also tried downgrading the versions of scanpy anndata and pandas to the ones mentioned here, and the problem persisted.
> On the other hand, I,m gonna try to run it in a server with better specs than my PC and I will let you know if we can discard the memory issues or not.
> 
> Thanks a lot for your attention.

I also have memory issue but it seems to be numpy's problem to me.
How about I open a new issue and ask if anyone has the same issue like us

**Comment by kyrenya** [comment]
Sorry for taking me so long to come back to this. 
Changed the machine, problem disappeared, so in my case, I think it was just memory issues! Thanks for your attention.
