### ISSUE TITLE
MAST returns natural log, not log2FC

### ISSUE THREAD

**Issue by le-ander** [theislab/single-cell-tutorial#20]
I have recently checked with the MAST developers what log basis they use to report logfoldchanges in MAST because I could not find that information anywhere. (https://github.com/RGLab/MAST/issues/112)

Turns out that given we provide (natural)log-normalised as an input to mast, the reported logfoldchanges are also on a natural log basis. I.e. they need to be devided by ln(2) to become log2FC.

I guess this will also be important to how you use those values in the notebook as well.

**Comment by LuckyMD** [comment]
Hey!

Thanks for the update. I do have a plot that assumes they are log2 FC values. Tbh, I don't think it changes the results though. The only difference is a scaling factor on the logFC values... in the notebook the absolute values don't really matter. I will adapt this though!

**Comment by LuckyMD** [comment]
will reopen this for now until it is fixed.

**Comment by LuckyMD** [comment]
Updated in #58
