### ISSUE TITLE
Error in differential expression analysis

### ISSUE THREAD

**Issue by Vyoming** [theislab/single-cell-tutorial#22]
Hello, I was using this workflow to analyze my data and everything was working perfectly until I reached the differential expression analysis. I am running the notebook on a mac os 10.12.6, the version of R that I am using is 3.6.1. 
I have identified that the error occurs in the first line and produces the following error message

```
%%R -i adata_test -o ent_de 

sca <- SceToSingleCellAssay(adata_test, class = "SingleCellAssay")
```
The following error message is produced
 ```
Error in (function (..., along = N, rev.along = NULL, new.names = NULL,  : 
  arg 'counts' is non-atomic
Calls: <Anonymous> ... callGeneric -> eval -> eval -> do.call -> do.call -> <Anonymous>
```
I thought the error might be a result of the fact that  after dividing the measured counts by the size factor adata.X is a numpy matrix instead of an array so I attempted to convert the matrix to an array by adding the npsqueeze(np.asarray( function in the second line 
```
adata_test = adata.copy()
adata_test.X = np.squeeze(np.asarray(adata.raw.X))
adata_test.obs['n_genes'] = (adata_test.X > 0).sum(1) 
```
Any help would be much appreciated

**Comment by LuckyMD** [comment]
Hi!

I'm glad that the notebook has helped you so far. It sounds to me as though this has to do with `adata.layer['counts']` after subsetting. Could you try to remove that layer and see if it works then?

I should probably update the notebook again soon.
