### ISSUE TITLE
Get environment setup info

### ISSUE THREAD

**Issue by mbuttner** [theislab/single-cell-tutorial#23]
Hi Malte,

I am walking myself through the environment setup that you described. I'd like to suggest the following in Step 2: 
In order to find out where the `sc-tutorial` environment is located, I suggest to run the command `conda info --envs`. It lists all installed environments and also shows, which one is active. That's probably more convenient than activating the `sc-tutorial` environment, check for the environment path with `echo $CONDA_PREFIX` and then deactivate again. 

Best,
Maren

**Comment by LuckyMD** [comment]
Thanks! Much more elegant this way!
