### ISSUE TITLE
R libraries not accessible

### ISSUE THREAD

**Issue by mumichae** [theislab/single-cell-tutorial#24]
When using R in anaconda, a warning that the libraries cannot be installed occurs. These libraries can be added only locally. In order to overcome this, it helps to change the `R_LIB` path in the activate script

**Comment by mumichae** [comment]
```
cd $CONDA_PREFIX
conda deactivate
vim etc/conda/activate.d/env_vars.sh
```
add
```
R_LIBS_OLD=$R_LIBS
export R_LIBS_OLD
export R_LIBS=""
```
and to ` etc/conda/activate.d/env_vars.sh` add:
```
R_LIBS=$R_LIBS_OLD
export R_LIBS
unset R_LIBS_OLD
```

**Comment by LuckyMD** [comment]
So you want to unset the `R_LIBS` env variable in the environment. I didn't have any issues with this on my side previously, but will test. Thanks for flagging!

**Comment by mumichae** [comment]
Yes, we only had this problem when working on the interactive server

**Comment by LuckyMD** [comment]
thanks for letting me know! Will check it there.

**Comment by giovp** [comment]
Same here, on Fedora 28 also had this issue, fixed it with @mumichae suggestion. 
After that, also had  the classic `libicui18n.so.64: cannot open shared object file: No such file or directory` and surprisingly fixed it with `conda install -c r r-stringi` plus a bunch of missing libraries.

**Comment by giovp** [comment]
Update, on the same Fedora 28, `from rpy2.robjects import pandas2ri` was throwing errors such as 
```
R[write to console]: Error: package or namespace load failed for ‘tools’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/icb/giovanni.palla/miniconda3/envs/sc/lib/R/library/tools/libs/tools.so':
  /home/icb/giovanni.palla/miniconda3/envs/sc/lib/R/library/tools/libs/tools.so: undefined symbol: R_NewPreciousMSet

R[write to console]: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/icb/giovanni.palla/miniconda3/envs/sc/lib/R/library/tools/libs/tools.so':
  /home/icb/giovanni.palla/miniconda3/envs/sc/lib/R/library/tools/libs/tools.so: undefined symbol: R_NewPreciousMSet
Calls: <Anonymous> -> loadNamespace -> library.dynam -> dyn.load
```
This is also a classic dynamic loading problem when working on servers. Workaround was looking where **tools.so** was pointing:
`R CMD ldd /home/icb/giovanni.palla/miniconda3/envs/sc/lib/R/library/tools/libs/tools.so`

and exporting the path, with:
`
export LD_LIBRARY_PATH=/home/icb/giovanni.palla/miniconda3/envs/sc/lib/R/library/tools/libs/../../../lib/:${LD_LIBRARY_PATH}
`. 
Again, this is most likely different for other users, just leaving it here for reference. Doesn't feel like a stable solution but it works...

**Comment by LuckyMD** [comment]
Thanks for further updates @giovp. It would be good to know which environment variables we might still be missing that are reset when moving to our new env. `R_LIBS` seems to be one... but I fail to see what you concluded for `tool.so` just `$HOME/miniconda3/envs/$CONDA_PREFIX/lib/`?

**Comment by LuckyMD** [comment]
You could probably just do
`export LD_LIBRARY_PATH=/home/icb/giovanni.palla/miniconda3/envs/sc/lib/R/lib/:${LD_LIBRARY_PATH}` to cut out the going back and forward in the directory, no?

I would have thought that a conda env would set up the environment variables correctly to link to the relevant libs, especially as they were installed via conda in the first place. Strange that this doesn't work...

**Comment by wangmhan** [comment]
Hi,

I'm using macOS and have the same problem. But cannot used the code as mentioned about to change etc/conda/activate.d/env_vars.sh
Is there any solutions for it?

Thanks a lot!

**Comment by giovp** [comment]
@LuckyMD that would probably work, will try out as soon as I have time.
@wangmhan would be useful to share the error message for debugging purposes

**Comment by wangmhan** [comment]
What I did on macOS is:

cd /Users/**/opt/anaconda3/envs/
conda deactivate
vim etc/conda/activate.d/env_vars.sh

the error message is:
"etc/conda/activate.d/env_vars.sh"
"etc/conda/activate.d/env_vars.sh" E212: Can't open file for writing

**Comment by mrichter23** [comment]
Hi, I got the same error as Giovanni:
`RRuntimeError: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/lib/R/library/tools/libs/tools.so':
  /usr/lib/R/library/tools/libs/tools.so: undefined symbol: R_NewPreciousMSet
Calls: <Anonymous> -> loadNamespace -> library.dynam -> dyn.load`

My output from `R CMD ldd /usr/lib/R/library/tools/libs/tools.so` :
`linux-vdso.so.1 (0x00007ffe0bf6e000)
	libR.so => /usr/lib/R/lib/libR.so (0x00007f15e6137000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f15e5d46000)
	libblas.so.3 => /usr/lib/x86_64-linux-gnu/libblas.so.3 (0x00007f15e5ad9000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f15e573b000)
	libreadline.so.7 => /lib/x86_64-linux-gnu/libreadline.so.7 (0x00007f15e54f2000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f15e5280000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f15e505a000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f15e4e4a000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f15e4c2d000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f15e4a25000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f15e4821000)
	libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007f15e446a000)
	libicui18n.so.60 => /usr/lib/x86_64-linux-gnu/libicui18n.so.60 (0x00007f15e3fc9000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f15e3d9a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f15e3b7b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f15e69d1000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f15e3951000)
	libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007f15e1da8000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f15e1a1f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f15e1807000)`

So I tried `export LD_LIBRARY_PATH=/usr/lib/R/lib/:${LD_LIBRARY_PATH}`
But this didn't solve the problem...
I'm a little lost with that, so any input/help on that would greatly be appreciated :cookie:

**Comment by giovp** [comment]
Try this:
`R CMD ldd /usr/lib/R/library/tools/libs/tools.so` and then export whatever you find there

Like this:
> This is also a classic dynamic loading problem when working on servers. Workaround was looking where **tools.so** was pointing:
> `R CMD ldd /home/icb/giovanni.palla/miniconda3/envs/sc/lib/R/library/tools/libs/tools.so`
> 
> and exporting the path, with:
> `export LD_LIBRARY_PATH=/home/icb/giovanni.palla/miniconda3/envs/sc/lib/R/library/tools/libs/../../../lib/:${LD_LIBRARY_PATH}`.

Also, I would strongly recommend you to make sure you installed all the R libraries in the specific conda environment where you have also R (an the rest of the python libraries).  

I see that now files are pointing to different folders already: e.g. `/lib/x86_64-linux-gnu` `/usr/lib`
and this will for sure create trouble in the future, like 100% they will.

Always do `.libPaths()` everytime you start an R session and make sure that all the libraries are always installed in the same path. You can modify the default R paths [like this](https://stackoverflow.com/questions/15170399/change-r-default-library-path-using-libpaths-in-rprofile-site-fails-to-work) and , in my experience, you will have to modify it (if you want at all) at every R session (cause for some reasons R in conda always fall back to standard libPaths, not sure why).

**Comment by mrichter23** [comment]
Thanks for the quick response. 
I had already done `R CMD ldd /usr/lib/R/library/tools/libs/tools.so` and exported what was there as I described before (I had tried both paths to be sure but only reported the one that was more likely to potentially fix the issue)
Update: It seems my environment R installation was corrupted:
```SafetyError: The package for r-base located at /home/maria/miniconda3/pkgs/r-base-3.6.1-h9bb98a2_1
appears to be corrupted. The path 'lib/R/doc/html/packages.html'
has an incorrect size.
  reported size: 2946 bytes
  actual size: 28743 bytes
```
I fixed this by removing the environment and doing a conda clean --packages --tarballs before reinstalling the environment.
However, this still didn't fix the issue and even though the R in my environment was always just pointing at one path to load libraries:
```> .libPaths()
[1] "/home/maria/miniconda3/envs/hep2/lib/R/library"
> 
``` 
It kept insisting to use tools.so from the /usr/lib path no matter what. 

In the end installing simplegeneric and tzlocal in my base environment solved the issue, but I still find this behaviour weird. Especially because all my packages are nicely installed in my specific environment and I don't have problems importing them now that I got rpy2 to work.

Btw, your files are also pointing to different directories and I think this is a normal R-thing in this context:
` /home/icb/giovanni.palla/miniconda3/envs/sc/lib/R/library/tools/libs/../../../lib/` and `/lib64/`

**Comment by genecell** [comment]
> You could probably just do
> `export LD_LIBRARY_PATH=/home/icb/giovanni.palla/miniconda3/envs/sc/lib/R/lib/:${LD_LIBRARY_PATH}` to cut out the going back and forward in the directory, no?
> 
> I would have thought that a conda env would set up the environment variables correctly to link to the relevant libs, especially as they were installed via conda in the first place. Strange that this doesn't work...

This directly solved the problem, cool and elegant!

**Comment by wangmhan** [comment]
I finally found that as I installed R first. Then, just don't install R
again through conda, the anaconda could find the existed R automatically.
That's my solution, but I don't know if could fit others or not.

**Comment by Manikgarg** [comment]
> As @LuckyMD mentioned:
> 
> > You could probably just do
> > `export LD_LIBRARY_PATH=/home/icb/giovanni.palla/miniconda3/envs/sc/lib/R/lib/:${LD_LIBRARY_PATH}` to cut out the going back and forward in the directory, no?
> > I would have thought that a conda env would set up the environment variables correctly to link to the relevant libs, especially as they were installed via conda in the first place. Strange that this doesn't work...
> 
> This directly solved the problem, cool and elegant!

This solved the issue for me. Thanks a lot!
