### ISSUE TITLE
Exception: Data must be 1-dimensional when plotting new marker genes in jupyter notebook

### ISSUE THREAD

**Issue by federicaress** [theislab/single-cell-tutorial#28]
I am following the notebook to understand the steps of single-cell RNA seq. 

I had the same [issue #21](https://github.com/theislab/single-cell-tutorial/issues/21#) for the version of scanpy, so I followed what is said in the answer.
It worked perfectly beside some problems that I solved and I want to write here so everyone that has the same issues can resolve them:

0. also `adata = adata.concatenate(adata_tmp, batch_key='sample_id')`and `adata.obs.drop(columns=['sample_id'], inplace=True)` generated errors so I commented out also those lines

1. I had errors when a graph is plotted using `sc.pl.palettes.godsnot_64` or `sc.pl.palettes.default_64` so I use `sc.pl.palettes.vega_20_scanpy ` instead

2. In the step  _Marker genes & cluster annotation_  I replaced:

```
adata.rename_categories('louvain_r0.5', ['TA', 'EP (early)', 'Stem', 'Goblet', 'EP (stress)', 'Enterocyte', 'Paneth', 'Enteroendocrine', 'Tuft']) 
```

with 

``` 
adata.rename_categories('louvain_r0.5', ['TA', 'EP (early)', 'Stem', 'Goblet', 'EP (stress)', 'Enterocyte', 'Paneth'])
```

because the number of old and new categories don't match, so that way it works.

3. When I run 
```
#Plot the new marker genes
sc.pl.rank_genes_groups(adata, key='rank_genes_r0.5_entero_sub', groups=['Enterocyte,0','Enterocyte,1','Enterocyte,2'], fontsize=12)
```
I get that  `no field of name Enterocyte,2`,  so I commented out that group and with the other two it works.

I get now to my problem. I am running the notebook with the case study data and with `scanpy==1.4.5.1 anndata==0.7.1 umap==0.3.10 numpy==1.18.1 scipy==1.4.1 pandas==0.25.3 scikit-learn==0.22.1 statsmodels==0.11.1 python-igraph==0.8.0 louvain==0.6.1`.
(Note: I use pandas 0.25.3 because previously, when I try to run it with 1.0.1 it had incompatibility problems) 

Now I have a problem in the steps of subclustering, when I try to run:
 ```
entero_clusts = [clust for clust in adata.obs['louvain_r0.5_entero_sub'].cat.categories if clust.startswith('Enterocyte')]
  for clust in entero_clusts:
     sc.pl.rank_genes_groups_violin(adata, use_raw=True, key='rank_genes_r0.5_entero_sub', groups=[clust], gene_names=adata.uns['rank_genes_r0.5_entero_sub']['names'][clust][90:100]) 

```
the error I get is
```

 ---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-58-4453b5691a91> in <module>
      2 
      3 for clust in entero_clusts:
----> 4     sc.pl.rank_genes_groups_violin(adata, use_raw=True, key='rank_genes_r0.5_entero_sub', groups=[clust], gene_names=adata.uns['rank_genes_r0.5_entero_sub']['names'][clust][90:100])
      5 

~/anaconda3/envs/sc-tutorial/lib/python3.8/site-packages/scanpy/plotting/_tools/__init__.py in rank_genes_groups_violin(adata, groups, n_genes, gene_names, gene_symbols, use_raw, key, split, scale, strip, jitter, size, ax, show, save)
    727             if issparse(X_col): X_col = X_col.toarray().flatten()
    728             new_gene_names.append(g)
--> 729             df[g] = X_col
    730         df['hue'] = adata.obs[groups_key].astype(str).values
    731         if reference == 'rest':

~/anaconda3/envs/sc-tutorial/lib/python3.8/site-packages/pandas/core/frame.py in __setitem__(self, key, value)
   3485         else:
   3486             # set column
-> 3487             self._set_item(key, value)
   3488 
   3489     def _setitem_slice(self, key, value):

~/anaconda3/envs/sc-tutorial/lib/python3.8/site-packages/pandas/core/frame.py in _set_item(self, key, value)
   3561         """
   3562 
-> 3563         self._ensure_valid_index(value)
   3564         value = self._sanitize_column(key, value)
   3565         NDFrame._set_item(self, key, value)

~/anaconda3/envs/sc-tutorial/lib/python3.8/site-packages/pandas/core/frame.py in _ensure_valid_index(self, value)
   3538         if not len(self.index) and is_list_like(value):
   3539             try:
-> 3540                 value = Series(value)
   3541             except (ValueError, NotImplementedError, TypeError):
   3542                 raise ValueError(

~/anaconda3/envs/sc-tutorial/lib/python3.8/site-packages/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
    312                     data = data.copy()
    313             else:
--> 314                 data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
    315 
    316                 data = SingleBlockManager(data, index, fastpath=True)

~/anaconda3/envs/sc-tutorial/lib/python3.8/site-packages/pandas/core/internals/construction.py in sanitize_array(data, index, dtype, copy, raise_cast_failure)
    727     elif subarr.ndim > 1:
    728         if isinstance(data, np.ndarray):
--> 729             raise Exception("Data must be 1-dimensional")
    730         else:
    731             subarr = com.asarray_tuplesafe(data, dtype=dtype)

Exception: Data must be 1-dimensional
```

I thought it was an issue for the cache but I cleaned it, restarted the kernel and cleared all outputs and the problem remains.
How can I fix this?

**Comment by LuckyMD** [comment]
Hi Federica, 

Thanks so much for the update on potential scanpy 1.4.5.1 changes. The clustering is typically never exactly the same on different systems. I think I mentioned this in the README as well. I have to make slight alterations to e.g. the random seed, or other parameters to get something similar again.

Your error seems to stem from the `clusts` variable. Could you check if you just use the first Enterocyte cluster in the list, you can plot?

**Comment by federicaress** [comment]
Thank you for the response.
I tried with `['Enterocyte,0']`, which is my first cluster and it doesn't work, unfortunately

**Comment by federicaress** [comment]
Okay, thanks.
Yes, it is present (and also it is present in previous chunks of code and it does function). 
Anyway I don't know how to report it in the scanpy package, should I report this exact error?
I'll retry to re-run the notebook with the ones which were used in the repo, just to be sure it's not a problem of my machine. I'll build another environment, so maybe I could try to fix this part in the previous environment.
Thanks again.

**Comment by federicaress** [comment]
Okay, thanks.
Yes, it is present (and also it is present in previous chunks of code and it does function). 
Anyway I don't know how to report it in the scanpy package, should I report this exact error?
I'll retry to re-run the notebook with the ones which were used in the repo, just to be sure it's not a problem of my machine. I'll build another environment, so maybe I could try to fix this part in the previous environment.
Thanks again.

**Comment by liekevandehaar** [comment]
Hi @federicaress , did you manage to solve your issue? I have a very similar problem and was wondering if and how you fixed it.

**Comment by LuckyMD** [comment]
Sorry for being slow to reply... a lot on my plate at the moment:

Could you check if you can run the simplified:
`sc.pl.rank_genes_groups_violin(adata, key='rank_genes_r0.5_entero_sub', groups=['Enterocyte,0'], gene_names=adata.uns['rank_genes_r0.5_entero_sub']['names']['Enterocyte,0'][:5])`

**Comment by liekevandehaar** [comment]
@LuckyMD no problem at all, thanks for your reply! I wrote because I have the same issue but in my own dataset. I expected that it had to do with the format of adata.X 
Interestingly, when I run your example when adata.X is transformed to an array, I get the error

```
adata.X = adata.X.toarray()
adata.X

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)
```
When I do not run `adata.X = adata.X.toarray()` and this is the shape of adata.X:
```

<2348x27998 sparse matrix of type '<class 'numpy.float32'>'
	with 4109917 stored elements in Compressed Sparse Row format>
```

the plotting is fine. My own data already from the moment of creating it is and array. When I run

```
from scipy.sparse import csr_matrix
adata.X = csr_matrix(adata.X)
```
The plotting works fine. So issue solved. I do however believe it has something to do with the upgrading to scanpy==1.4.5.1 because before the plotting when adata was an array was fine.

**Comment by LuckyMD** [comment]
That's really interesting. I'm not aware of sparse data requirements changing in the new scanpy. Could you make a minimal reproducible example of this using for example `sc.datasets.pbmc68k_reduced()`? That would be a good bug report for scanpy.

**Comment by suzhanhao** [comment]
Same issue here. This bug is caused by the transformation from sparse count matrices to dense matrix in adata.X at the very beginning of the data import session in the tutorial notebook:
```
#Load data
adata = sc.read(data_file, cache=True)
adata = adata.transpose()
adata.X = adata.X.toarray()
```
**For those who ran into the same issue, try the following modification of your code.**
First convert adata.X back to the sparse matrix :
 ```
from scipy import sparse 
adata.X = sparse.csc_matrix(adata.X)
```
and then set `use_raw=False` in `sc.pl.rank_genes_groups_violin()`:
```
entero_clusts = [clust for clust in adata.obs['louvain_r0.5_entero_sub'].cat.categories if clust.startswith('Enterocyte')]

for clust in entero_clusts:
    sc.pl.rank_genes_groups_violin(adata, use_raw=False, key='rank_genes_r0.5_entero_sub', groups=[clust], 
                                   gene_names=adata.uns['rank_genes_r0.5_entero_sub']['names'][clust][90:100])
```
Then everything would work fine !!

**Comment by LuckyMD** [comment]
Thank you @suzhanhao. Indeed sparse matrix compatibility in rpy2 and anndata2ri has improved since I made this workflow.

**Comment by jorvis** [comment]
Interesting that we're getting this error even if we open forcing sparse:

`adata = ana.get_adata(force_sparse=True)`

**Comment by LuckyMD** [comment]
@jorvis does the specific transformation via `sparse.csc_matrix(adata.X)` suggested above solve the issue for you?

**Comment by jorvis** [comment]
It did, yes, thank you!

**Comment by hhhh1230511** [comment]
Hi I got the same issue. I imported  a csv file to scanpy, everything works fine except for the 'sc.pl.rank_genes_groups_violin(adata, groups='0',n_genes=8)'. I checked the adata.X, it is not a sparse. However, when I try to get adata.raw.X, it is not a sparse format, so it is unable to output the plot. Could you fix it?

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\10299392\AppData\Local\r-miniconda\lib\site-packages\scanpy\plotting\_tools\__init__.py", line 909, in rank_genes_groups_violin
    df[g] = X_col
  File "C:\Users\10299392\AppData\Local\r-miniconda\lib\site-packages\pandas\core\frame.py", line 3040, in __setitem__
    self._set_item(key, value)
  File "C:\Users\10299392\AppData\Local\r-miniconda\lib\site-packages\pandas\core\frame.py", line 3115, in _set_item
    self._ensure_valid_index(value)
  File "C:\Users\10299392\AppData\Local\r-miniconda\lib\site-packages\pandas\core\frame.py", line 3166, in _ensure_valid_index
    value = Series(value)
  File "C:\Users\10299392\AppData\Local\r-miniconda\lib\site-packages\pandas\core\series.py", line 327, in __init__
    data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
  File "C:\Users\10299392\AppData\Local\r-miniconda\lib\site-packages\pandas\core\construction.py", line 496, in sanitize_array
    raise Exception("Data must be 1-dimensional")
Exception: Data must be 1-dimensional

**Comment by LuckyMD** [comment]
Hi @hhhh1230511, I think your issue might be one with scanpy rather than with the single-cell-tutorial. Please report it there instead.
