### ISSUE TITLE
Error in grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : Polygon edge not found

### ISSUE THREAD

**Issue by ld2113** [theislab/single-cell-tutorial#3]
I have encountered the following error when trying to execute the notebook cells which visualise the monocle2 output:

**Error in grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : Polygon edge not found**

I am on macOS Mojave and R version 3.5.1 witb Bioconductor 3.7 and Monocle version 2.8.0 and Anaconda Python 3.6

Furthermore: scanpy==1.3.7 anndata==0.6.17 numpy==1.15.4 scipy==1.1.0 pandas==0.23.4 scikit-learn==0.20.2 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1

**Comment by ld2113** [comment]
This turns out to be a problem related to Micrisoft Office for Mac and it's replacement for the systemwide Arial font. See here for a solution: 

https://stackoverflow.com/questions/10581440/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon

**Comment by LuckyMD** [comment]
Thanks for posting this Leander!
