### ISSUE TITLE
TypeError: Callable[[arg, ...], result]: each arg must be a type. Got Ellipsis.

### ISSUE THREAD

**Issue by jjaa-mp** [theislab/single-cell-tutorial#33]
Hi,

I was following the latest notebook and I successfully installed all the packages required to complete the tutorial. However, I find the following error when running the first chunk of code of section 2.5 Visualization:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-33-fab320f7c66e> in <module>
      3 sc.pp.neighbors(adata)
      4 
----> 5 sc.tl.tsne(adata, n_jobs=12) #Note n_jobs works for MulticoreTSNE, but not regular implementation)
      6 sc.tl.umap(adata)
      7 sc.tl.diffmap(adata)

~/anaconda3/lib/python3.7/site-packages/scanpy/tools/_tsne.py in tsne(adata, n_pcs, use_rep, perplexity, early_exaggeration, learning_rate, random_state, use_fast_tsne, n_jobs, copy)
    108     if X_tsne is None:
    109         from sklearn.manifold import TSNE
--> 110         from . import _tsne_fix  # fix by D. DeTomaso for sklearn < 0.19
    111 
    112         # unfortunately, sklearn does not allow to set a minimum number

~/anaconda3/lib/python3.7/site-packages/scanpy/tools/_tsne_fix.py in <module>
     32     verbose: int = 0,
     33     args: Iterable[Any] = (),
---> 34     kwargs: Mapping[str, Any] = MappingProxyType({}),
     35 ) -> Tuple[np.ndarray, float, int]:
     36     """\

~/anaconda3/lib/python3.7/typing.py in __getitem__(self, params)
    756                                 f" Got {args}")
    757             params = (tuple(args), result)
--> 758         return self.__getitem_inner__(params)
    759 
    760     @_tp_cache

~/anaconda3/lib/python3.7/typing.py in inner(*args, **kwds)
    252         except TypeError:
    253             pass  # All real errors (not unhashable args) are raised below.
--> 254         return func(*args, **kwds)
    255     return inner
    256 

~/anaconda3/lib/python3.7/typing.py in __getitem_inner__(self, params)
    779                 return self.copy_with((_TypingEllipsis, result))
    780             msg = "Callable[[arg, ...], result]: each arg must be a type."
--> 781             args = tuple(_type_check(arg, msg) for arg in args)
    782             params = args + (result,)
    783             return self.copy_with(params)

~/anaconda3/lib/python3.7/typing.py in <genexpr>(.0)
    779                 return self.copy_with((_TypingEllipsis, result))
    780             msg = "Callable[[arg, ...], result]: each arg must be a type."
--> 781             args = tuple(_type_check(arg, msg) for arg in args)
    782             params = args + (result,)
    783             return self.copy_with(params)

~/anaconda3/lib/python3.7/typing.py in _type_check(arg, msg, is_argument)
    140         return arg
    141     if not callable(arg):
--> 142         raise TypeError(f"{msg} Got {arg!r:.100}.")
    143     return arg
    144 

TypeError: Callable[[arg, ...], result]: each arg must be a type. Got Ellipsis.

--

I couldn't find a possible solution. Could you provide any hints? Thanks in advance.

--
I'm working on the Google Cloud Platform (Ubuntu instance). Here is my IPython.sys_info() : 

{'commit_hash': 'c233c25ab',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': 'home/user/anaconda3/lib/python3.7/site-packages/IPython',
 'ipython_version': '7.8.0',
 'os_name': 'posix',
 'platform': 'Linux-5.0.0-1033-gcp-x86_64-with-debian-buster-sid',
 'sys_executable': 'home/user/anaconda3/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.7.4 (default, Aug 13 2019, 20:35:49) \n[GCC 7.3.0]'}

**Comment by LuckyMD** [comment]
Hi,

It looks like you've updated scanpy to version 1.4.5.post1. There is a fix for this in 1.4.5.1 (https://github.com/theislab/scanpy/issues/1067). So either you can upgrade scanpy again, or you can downgrade to the version stated in the `latest_notebook`` folder. I will try to update this in the coming weeks and release a docker so things should get easier.
