### ISSUE TITLE
Different outputs

### ISSUE THREAD

**Issue by evenDDDDD** [theislab/single-cell-tutorial#36]
Hi!
When I try to repeat the entire process, including QC, normalization, batch correction, dimensionality reduction, clustering, difference analysis, I use the same input file and almost the same parameters, why do I get obvious different results? Among the differences between my use and the tutorial are the software version updates I use. 

Different results include that cluster 0 has 4000+ cells, and the top 20 differentially expressed genes contain many mitochondrial and ribosomal genes. And some difference can be seen on all output graphs, even if the QC graph is not particularly obvious.

Looking forward to getting a reply！
Thanks！

**Comment by LuckyMD** [comment]
Hi @evenDDDDD,
Scanpy's code is not 100% reproducible when you go to different systems or update packages. I believe I wrote a bit about this in the README as well. Please check that out. 

Briefly, this has to do with numerical libraries that you use being slightly different in different package versions and systems. So you will have to make small adjustments to the random seeds, or to the clustering resolution, etc to get the same results. The results should however be qualitatively similar. There are discussions on this in Scanpy issues: https://github.com/theislab/scanpy/issues/1187 and https://github.com/theislab/scanpy/issues/313. 

We now also have a docker image that is available for the tutorial environment, if you would like to use that. There is still no guarantee on perfect reproducibility (PCA seems to have some inherent differences across systems even in the same docker container), but it will help.

**Comment by evenDDDDD** [comment]
Thank you very much for your reply. I think this is really a very important reason.

In addition, when I analyzed my own data, I found that the proportion of mitochondrial genes in the output figure of sc.pl.umap (adata, color = ['log_counts','mt_frac ']) was very large, and the mitochondrial and ribosome genes in the gene (MAST) of top20 from the difference analysis between the experimental group and the control group also accounted for a large proportion. The filter threshold I set is adata. OBS ['mt_frac '] < 0.15, because most of the cells are below 15%.

Can you give me some advice on this?

Thank you very much for your reply

**Comment by LuckyMD** [comment]
Ribosomal and mitochondrial genes are not only QC covariates, but they can also be meaningful biological signals. It seems you have a different MT expression between your conditions. That may be meaningful.
