### ISSUE TITLE
mt fraction calculation

### ISSUE THREAD

**Issue by giovp** [theislab/single-cell-tutorial#39]
In case you are planned to update tutorial at some point, Isaac pointed me to a cleaner way to calculate mt fraction.
```python
adata.var["mt"] = adata.var_names.str.startswith("MT-")
sc.pp.calculate_qc_metrics(adata, qc_vars=["mt"], inplace=True)
```
It calculates both `total_counts_mt` and `pct_counts_mt`

just leaving it here as reference.

**Comment by LuckyMD** [comment]
yes, this function was added after the tutorial was finished ;). Thanks, though! Will leave this issue open for the grand update!

**Comment by LuckyMD** [comment]
Updated in #58
