### ISSUE TITLE
Jupyter notebook kernel crashes silently: Intel OMP

### ISSUE THREAD

**Issue by ld2113** [theislab/single-cell-tutorial#4]
When trying to call scran for the normalisation step in the notebook, the kernel of the notebook dies without producing any error in the notebook.

When checking the jupyter notebook server output, Ican see the following messages:

`OMP: Error #15: Initializing libomp.dylib, but found libiomp5.dylib already initialized.
OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
[I 18:24:28.130 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports`

I am on macOS Mojave and R version 3.5.1 with Bioconductor 3.7, scran version 1.8.4 and Anaconda Python 3.6

Furthermore: scanpy==1.3.7 anndata==0.6.17 numpy==1.15.4 scipy==1.1.0 pandas==0.23.4 scikit-learn==0.20.2 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1

**Comment by LuckyMD** [comment]
Hey!

Thanks for posting this. It looks like you may have openmp libs installed via anaconda, and system openmp libs interfere with this. You could also try uninstalling some anaconda libs to see if that helps...

**Comment by ld2113** [comment]
I tried uninstalling conda libs as well as other libs with before. None of those seemed to fix this problem though.

**Comment by charlotterich** [comment]
Did you ever work this out? I'm struggling with the same problem.

**Comment by le-ander** [comment]
This did the job for me:
```python
import os
os.environ['KMP_DUPLICATE_LIB_OK']='TRUE'
```
Not great but seems to work fine.
