### ISSUE TITLE
Kernel restarting when concatenating

### ISSUE THREAD

**Issue by omanor** [theislab/single-cell-tutorial#42]
Hi,

I used the docker container provided to set up the environment which was fast and easy, thanks!

However, when I start running the notebook, the cell starting with "# Loop to load rest of data sets" in the first section (reading the data) keeps crashing the kernel (tried several times with the same result). I added some printouts to narrow it down to the "# Concatenate to main adata object" section. Not sure why this is happening. Any insight on what could be causing this?

Thanks!
Ohad

**Comment by LuckyMD** [comment]
Hi, This sounds like you don't have sufficient memory on your system. Are you running this on a server? That's typically when the kernel crashes for me.

**Comment by omanor** [comment]
Hi, I was running it locally so that might be the issue. I will try running it again on a machine with more RAM and let you know if the issue occurs again. Thanks!

**Comment by LuckyMD** [comment]
It sounds like this was solved. Will close for now.
