### ISSUE TITLE
Problems when installing package"Slingshot"and "Monocle"

### ISSUE THREAD

**Issue by satellite119** [theislab/single-cell-tutorial#43]
I am following the "Scripts for "Current best-practices in single-cell RNA-seq: a tutorial"". The environment is set up successfully and can works for my single-cell data and produce many useful results. But when I installed the "Slingshot" or "Monocle", there is an error: Warning message: “dependency ‘XML’ is not available”. 
Some people told me maybe the R version in the "sc_tutorial_environment.yml" is low, now it is 3.5.1(2018-7-2), not compatible with the latest version of "Slingshot" or "Monocle".  But if R is upgraded to 4.0,  the python program RPY2 will not be compatible with R 4.0 as well. I am not sure how to solve the problem?

Thanks

**Comment by LuckyMD** [comment]
Hey @satellite119,

Could you not just `conda install libxml2` to solve your issue?

We have unfortunately not updated the notebook dependencies in a while, but we have been using the notebook with the latest versions of scanpy, anndata, and other packages with some minor adaptations. I'm not aware that `rpy2` is not compatible with R 4.0. I've not found this after a quick google either. Are you sure that that is the case? If it really doesn't work with R 4.0, then i would maybe downgrade to R 3.6, as `rpy2` is a central component to move between `python` and `R` in this notebook. We have been using the notebook with `R 3.6` successfully internally.

Hope this helps!

**Comment by satellite119** [comment]
Thank you for the help. 
I typed " conda install libxml2" under  "Python [conda env:.conda-scanpy]", it is installed successfully. Then I typed "BiocManager::install(c('slingshot'))" under "R [conda env:.conda-scanpy]", but the same error occured again. 

Bioconductor version 3.8 (BiocManager 1.30.10), R 3.5.1 (2018-07-02)
Installing package(s) 'slingshot'
Warning message:
“dependency ‘XML’ is not available”
also installing the dependencies ‘annotate’, ‘RNeXML’, ‘genefilter’, ‘phylobase’, ‘zinbwave’, ‘clusterExperiment’
Warning message in install.packages(...):
“installation of package ‘annotate’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘RNeXML’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘genefilter’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘phylobase’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘zinbwave’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘clusterExperiment’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘slingshot’ had non-zero exit status”
Updating HTML index of packages in '.Library'
Making 'packages.html' ...
 done
Old packages: 'dplyr', 'tidyr'

I will deeply appreciate your reply.
Thanks

**Comment by LuckyMD** [comment]
If you have libxml2 installed via `conda` or `apt-get` or other, then you should have the dependency. I'm not sure why `R` cannot find this package on your system. You may have to remove `R` and reinstall it after the `libxml2` library was installed? Conda with `R` can be difficult.

**Comment by satellite119** [comment]
Do you know how to upgrade R version under "R [conda env:.conda-scanpy]" successfully? 
Thanks

**Comment by LuckyMD** [comment]
You would have to have to install a different `r-base` and `r-essentials` package via `conda install`.

**Comment by nkanrar** [comment]
What worked for me was doing conda install -c r r-xml

**Comment by satellite119** [comment]
> What worked for me was doing conda install -c r r-xml

It works successfully, thank you so much.

**Comment by LuckyMD** [comment]
Thanks for the update @nkanrar!
