### ISSUE TITLE
Dockerfile is not visible

### ISSUE THREAD

**Issue by serverhorror** [theislab/single-cell-tutorial#45]
Hello,

We are trying to run your pipeline. Unfortunately the image is not working when run from singularity and we cannot look into it since the source code is not available.

Please help being able to run this and provide the full source code to this.

**Comment by LuckyMD** [comment]
That's a very good point. Thanks for bringing that up! @le-ander do you think you could put the Dockerfile you used to generate the docker image on the docker hub or in the repo?

**Comment by le-ander** [comment]
Hey guys
I haven't managed to add it to the dockerhub page directly.
Made it available here instead: le-ander.github.io/documents/Dockerfile

**Comment by LuckyMD** [comment]
Do you want to add this to the repo maybe?

**Comment by le-ander** [comment]
Haven't figured out how you can do this yet, I think you need to build directly from the github repo or sthg. cannot just add it to an existing image as far as I understand

**Comment by LuckyMD** [comment]
No, I meant just adding the dockerfile and not the image to the repo. That way others can build the image from the file if needed.

**Comment by LuckyMD** [comment]
And on the Docker hub you typically add the Dockerfile to the description of the image.

**Comment by le-ander** [comment]
> No, I meant just adding the dockerfile and not the image to the repo. That way others can build the image from the file if needed.

Hm, I'm confused. Which repo are you referring to here?

**Comment by LuckyMD** [comment]
the one we're in right now ;)
