### ISSUE TITLE
adata.concatenate

### ISSUE THREAD

**Issue by mabaoweibbq** [theislab/single-cell-tutorial#48]
[hi]

#  Loop to load rest of data sets
#  Concatenate to main adata object
    adata = adata.concatenate(adata_tmp, batch_key='sample_id')

When I conducted that，it remind me 
![image](https://user-images.githubusercontent.com/53936765/95837009-b0e28480-0d72-11eb-8308-217482720953.png)

 Any insight on what could be causing this?

Thanks!
Ohad

**Comment by mabaoweibbq** [comment]
G:\ML\conda\lib\site-packages\pandas\core\indexes\base.py in get_indexer(self, target, method, limit, tolerance)
   2985         if not self.is_unique:
   2986             raise InvalidIndexError(
-> 2987                 "Reindexing only valid with uniquely valued Index objects"
   2988             )
   2989 

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

**Comment by mabaoweibbq** [comment]
There are only two samples for Concatenate，it caused the bug
 'Duo_M1', 'Duo_M2'

**Comment by mabaoweibbq** [comment]
'Duo_M1'-----adata
adata.shape
(2348, 27998)
AnnData object with n_obs × n_vars = 2348 × 27998
    obs: 'sample', 'region', 'donor'
    var: 'gene_id'


Duo_M2-----adata
(2206, 27998)
AnnData object with n_obs × n_vars = 2206 × 27998
    obs: 'sample', 'region', 'donor'
    var: 'gene_id'

**Comment by LuckyMD** [comment]
Please check issues #41 and #44 for solutions.
