### ISSUE TITLE
InvalidIndexError: Reindexing only valid with uniquely valued Index objects

### ISSUE THREAD

**Issue by 814471489** [theislab/single-cell-tutorial#50]
Hello, 

Thank you for your excellent work, but I ran into a bug while running your code. Could you please help me solve such a mistake? (InvalidIndexError: Reindexing only valid with uniquely valued Index objects) 
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/49757159/99495561-cec48a00-29ad-11eb-9392-3a27e5d70db9.png">

Thanks.

Best, Tian.

**Comment by LuckyMD** [comment]
Hi @814471489,

Which version of scanpy and anndata are you using? Could you run `adata.obs_names_make_unique()` before concatenating to see if it improves?

**Comment by 814471489** [comment]
> Hi @814471489,
> 
> Which version of scanpy and anndata are you using? Could you run `adata.obs_names_make_unique()` before concatenating to see if it improves?

Hello, this is the version I'm using.

![image](https://user-images.githubusercontent.com/49757159/99528031-a4d48d00-29d8-11eb-9329-ce9bd100f73d.png)

**Comment by LuckyMD** [comment]
Could you check whether you get the same error with anndata version 0.7.1 or below?

**Comment by Tsy97** [comment]
run` adata.var_names_make_unique()` before concatenating solved my problem.
