### ISSUE TITLE
no latest tag for Docker container

### ISSUE THREAD

**Issue by Zethson** [theislab/single-cell-tutorial#56]
Dear @le-ander and @LuckyMD,

to get a head start on my SC analysis adventures I wanted to complete the tutorial.
However, when attempting to pull the container via:

```
docker pull leanderd/single-cell-analysis                                                                                                                              
```
I encountered

`Error response from daemon: manifest for leanderd/single-cell-analysis:latest not found: manifest unknown: manifest unknown`

The reason for this behaviour is that by default Docker looks for the `latest` tag if no tag was specified.
However, you only have an explicit tag of `200402`. It is pretty much standard to always have a latest tag, which corresponds to the latest release and I would like to suggest to add a latest tag.

**Comment by LuckyMD** [comment]
yes, there should ofc be a `latest` tag. Thanks for highlighting!

**Comment by le-ander** [comment]
here you go ;)
https://hub.docker.com/r/leanderd/single-cell-analysis/tags?page=1&ordering=last_updated
