### ISSUE TITLE
Aesthetics must be either length 1 or the same as the data (87): fill

### ISSUE THREAD

**Issue by ld2113** [theislab/single-cell-tutorial#6]
I have encountered the following error when trying to execute the first code cell in the Metastable States section (3.5.6):

```
Error: Aesthetics must be either length 1 or the same as the data (87): fill
```
Furthermore:
```
RRuntimeError: Error in dev.off() : 
  QuartzBitmap_Output - unable to open file '/var/folders/pp/bph3z1rx3zs9m5j97r9qslxctsft0g/T/tmp3u47ajsw/Rplots001.png'
```

I am on macOS Mojave and R version 3.5.1 with Bioconductor 3.7 and Anaconda Python 3.6

Furthermore: scanpy==1.3.7 anndata==0.6.17 numpy==1.15.4 scipy==1.1.0 pandas==0.23.4 scikit-learn==0.20.2 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1

**Comment by LuckyMD** [comment]
This seems to be an issue only with the updated software (R 3.5, bioconductor 3.7, etc.). Interestingly adding this line breaks the current version of the tutorial with R 3.4.3.

This will be investigated.

**Comment by LuckyMD** [comment]
It looks like this has to do with an update of how ggplot2's `qplot` bins the pseudotime values by default between bioconductor versions. It appears stable between R 3.5 and 3.5.1 (over bioconductor 3.7 and 3.8).

**Comment by le-ander** [comment]
Just wanted to flag that in the current version of the notebook, this error reappears with bioconduction version 3.10 (the version on the charliecloud images I made)

**Comment by LuckyMD** [comment]
great... so basically depending on the version of bioconductor you have to switch between the two `df['bins']` lines above.
