### ISSUE TITLE
%%R -i data_mat -i input_groups -o size_factors 

### ISSUE THREAD

**Issue by allisoncheney** [theislab/single-cell-tutorial#60]
Thanks for creating such an excellent tutorial. 

I run into an error when running this cell.
```
%%R -i data_mat -i input_groups -o size_factors 
size_factors = computeSumFactors(data_mat, clusters=input_groups, min.mean=0.1)
```
I get this error: 
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘assay’ for signature ‘"matrix", "character"’

I am using the docker container here: https://hub.docker.com/r/leanderd/single-cell-analysis
I'm using a Mac.

I thought it might be an R version problem, so I also tried not using the docker and installing the package requirements manually with an earlier version of R, but as you might imagine package conflicts made it impossible to install the required packages using BiocManager.

**Comment by LuckyMD** [comment]
Ah, you seem to be the victim of an updated docker container with a notebook that hasn't been updated yet. I'm still reviewing the new code update to make sure we can update this. The new version of scran expects a SingleCellExperiment object rather than just a data matrix.

You can adapt the above by replacing the offending line with:
`size_factors = sizeFactors(computeSumFactors(SingleCellExperiment(list(counts=data_mat)), clusters=input_groups, min.mean=0.1))`

**Comment by oligomyeggo** [comment]
Sorry for opening up this issue again, but I am having a related problem. I was initially having the same issue as first described here, but the fix @LuckyMD provided worked great! However, now I am working on a different project using the same environment and code as I was previously (version control via pipenv), and I am getting a new error: 

My code (follows the Single Best Practices Tutorial):
```
%%R -i data_mat -i input_groups -o size_factors

size_factors = sizeFactors(computeSumFactors(SingleCellExperiment(list(counts=data_mat)), clusters=input_groups, min.mean=0.1))
```

Error:
```
RRuntimeError: Error in validObject(.Object) : 
  invalid class “dgCMatrix” object: 1: invalid object for slot "i" in class "dgCMatrix": got class "array", should be or extend class "integer"
invalid class “dgCMatrix” object: 2: invalid object for slot "p" in class "dgCMatrix": got class "array", should be or extend class "integer"
invalid class “dgCMatrix” object: 3: invalid object for slot "Dim" in class "dgCMatrix": got class "array", should be or extend class "integer"
invalid class “dgCMatrix” object: 4: invalid object for slot "x" in class "dgCMatrix": got class "array", should be or extend class "numeric"
```

I haven't updated or changed any versions from my previous analysis iteration, so I am not sure why I am not receiving this error.

**Comment by MeiYihan416** [comment]
> Ah, you seem to be the victim of an updated docker container with a notebook that hasn't been updated yet. I'm still reviewing the new code update to make sure we can update this. The new version of scran expects a SingleCellExperiment object rather than just a data matrix.
> 
> You can adapt the above by replacing the offending line with: `size_factors = sizeFactors(computeSumFactors(SingleCellExperiment(list(counts=data_mat)), clusters=input_groups, min.mean=0.1))`

Thank you for your great tutorial! I have read issue#60，but i also met some problems.
I run like this:
%%R -i data_mat -i input_groups -o size_factors

size_factors = sizeFactors(computeSumFactors(SingleCellExperiment(list(counts=data_mat)), clusters=input_groups, min.mean=0.1))

but i got the error:
RRuntimeError                             Traceback (most recent call last)
/tmp/ipykernel_98522/704539900.py in <module>
----> 1 get_ipython().run_cell_magic('R', '-i data_mat -i input_groups -o size_factors', '\nsize_factors = sizeFactors(computeSumFactors(SingleCellExperiment(list(counts=data_mat)), clusters=input_groups, min.mean=0.1))\n')

~/.local/lib/python3.9/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2417             with self.builtin_trap:
   2418                 args = (magic_arg_s, cell)
-> 2419                 result = fn(*args, **kwargs)
   2420             return result
   2421 

~/.local/lib/python3.9/site-packages/decorator.py in fun(*args, **kw)
    230             if not kwsyntax:
    231                 args, kw = fix(args, kw, sig)
--> 232             return caller(func, *(extras + args), **kw)
    233     fun.__name__ = func.__name__
    234     fun.__doc__ = func.__doc__

~/.local/lib/python3.9/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/.local/lib/python3.9/site-packages/rpy2/ipython/rmagic.py in R(self, line, cell, local_ns)
    735                         raise NameError("name '%s' is not defined" % input)
    736                 with localconverter(converter) as cv:
--> 737                     ro.r.assign(input, val)
    738 
    739         if args.display:

~/.local/lib/python3.9/site-packages/rpy2/robjects/functions.py in __call__(self, *args, **kwargs)
    196                 v = kwargs.pop(k)
    197                 kwargs[r_k] = v
--> 198         return (super(SignatureTranslatedFunction, self)
    199                 .__call__(*args, **kwargs))
    200 

~/.local/lib/python3.9/site-packages/rpy2/robjects/functions.py in __call__(self, *args, **kwargs)
    115 
    116     def __call__(self, *args, **kwargs):
--> 117         new_args = [conversion.py2rpy(a) for a in args]
    118         new_kwargs = {}
    119         for k, v in kwargs.items():

~/.local/lib/python3.9/site-packages/rpy2/robjects/functions.py in <listcomp>(.0)
    115 
    116     def __call__(self, *args, **kwargs):
--> 117         new_args = [conversion.py2rpy(a) for a in args]
    118         new_kwargs = {}
    119         for k, v in kwargs.items():

/usr/local/python3/lib/python3.9/functools.py in wrapper(*args, **kw)
    875                             '1 positional argument')
    876 
--> 877         return dispatch(args[0].__class__)(*args, **kw)
    878 
    879     funcname = getattr(func, '__name__', 'singledispatch function')

~/.local/lib/python3.9/site-packages/anndata2ri/scipy2ri/py2r.py in wrapper(obj)
     41 
     42         with localconverter(default_converter + numpy2ri.converter):
---> 43             return f(obj)
     44 
     45     return wrapper

~/.local/lib/python3.9/site-packages/anndata2ri/scipy2ri/py2r.py in csc_to_rmat(csc)
     51     csc.sort_indices()
     52     t, conv_data, _ = get_type_conv(csc.dtype)
---> 53     return methods.new(
     54         f"{t}gCMatrix",
     55         i=as_integer(csc.indices),

~/.local/lib/python3.9/site-packages/rpy2/robjects/functions.py in __call__(self, *args, **kwargs)
    196                 v = kwargs.pop(k)
    197                 kwargs[r_k] = v
--> 198         return (super(SignatureTranslatedFunction, self)
    199                 .__call__(*args, **kwargs))
    200 

~/.local/lib/python3.9/site-packages/rpy2/robjects/functions.py in __call__(self, *args, **kwargs)
    123             else:
    124                 new_kwargs[k] = conversion.py2rpy(v)
--> 125         res = super(Function, self).__call__(*new_args, **new_kwargs)
    126         res = conversion.rpy2py(res)
    127         return res

~/.local/lib/python3.9/site-packages/rpy2/rinterface_lib/conversion.py in _(*args, **kwargs)
     43 def _cdata_res_to_rinterface(function):
     44     def _(*args, **kwargs):
---> 45         cdata = function(*args, **kwargs)
     46         # TODO: test cdata is of the expected CType
     47         return _cdata_to_rinterface(cdata)

~/.local/lib/python3.9/site-packages/rpy2/rinterface.py in __call__(self, *args, **kwargs)
    678             )
    679             if error_occured[0]:
--> 680                 raise embedded.RRuntimeError(_rinterface._geterrmessage())
    681         return res
    682 

RRuntimeError: Error in validObject(.Object) : 
  invalid class “dgCMatrix” object: 1: invalid object for slot "i" in class "dgCMatrix": got class "array", should be or extend class "integer"
invalid class “dgCMatrix” object: 2: invalid object for slot "p" in class "dgCMatrix": got class "array", should be or extend class "integer"
invalid class “dgCMatrix” object: 3: invalid object for slot "Dim" in class "dgCMatrix": got class "array", should be or extend class "integer"
invalid class “dgCMatrix” object: 4: invalid object for slot "x" in class "dgCMatrix": got class "array", should be or extend class "numeric"
i use Linux Centos7, python 3.9.9 , R4.0.5 and rpy2 3.4.5

I don't know how to deal with it and thank you a lot for your help! @LuckyMD

**Comment by LuckyMD** [comment]
This looks like an issue with rpy2 3.4.3 and above that was reported in the anndata2ri repo already here: https://github.com/theislab/anndata2ri/issues/63

Please try downgrading rpy2 to 3.4.2 to see if that fixes your issue.
