### ISSUE TITLE
 R language in .py file

### ISSUE THREAD

**Issue by lu77777777** [theislab/single-cell-tutorial#62]
Hi, Thanks for this detailed tutorial,

I want check the detailed information in Pycharm to monitor the variable changes.

But it seems a little bit wrong for R language.

I tried
Rrequire('scran,RColorBrewer,slingshot,monocle,gam,ggplot2,plyr,MAST,clusterExperiment')
Rcode(size_factors = sizeFactors(computeSumFactors(SingleCellExperiment(list(counts=data_mat)), clusters=input_groups, min.mean=0.1)))

it will throw out the error messages
File "/data/lu/projects/test/main.py", line 198
    Rcode(size_factors = sizeFactors(computeSumFactors(SingleCellExperiment(list(counts=data_mat)), clusters=input_groups, min.mean=0.1)))
                                                                                                                           ^
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?

Do you know how to write the R language in pycharm?

**Comment by LuckyMD** [comment]
Sorry, I haven't tried to use `rpy2` in pycharm before. Not sure how this would work.
