### ISSUE TITLE
%%R -i data_mat -i input_groups -o size_factors size_factors = computeSumFactors(data_mat, clusters=input_groups, min.mean=0.1)

### ISSUE THREAD

**Issue by lu77777777** [theislab/single-cell-tutorial#63]
Hi，thanks for your detailed tutorial.

I run this sentences, but it seems a little bit wrong 
%%R -i data_mat -i input_groups -o size_factors
size_factors = computeSumFactors(data_mat, clusters=input_groups, min.mean=0.1)

the error message is 
---------------------------------------------------------------------------
RParsingError                             Traceback (most recent call last)
<ipython-input-22-3d6244253ca7> in <module>
----> 1 get_ipython().run_cell_magic('R', '-i data_mat -i input_groups -o size_factors', 'size_factors = computeSumFactors(data_mat, clusters=input_groups, min.mean=0.1)\nprint lei\n')

/data/lu/anaconda3/envs/renv/lib/python3.8/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2397             with self.builtin_trap:
   2398                 args = (magic_arg_s, cell)
-> 2399                 result = fn(*args, **kwargs)
   2400             return result
   2401 

<decorator-gen-121> in R(self, line, cell, local_ns)

/data/lu/anaconda3/envs/renv/lib/python3.8/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/data/lu/anaconda3/envs/renv/lib/python3.8/site-packages/rpy2/ipython/rmagic.py in R(self, line, cell, local_ns)
    761                     return_output = False
    762             else:
--> 763                 text_result, result, visible = self.eval(code)
    764                 text_output += text_result
    765                 if visible:

/data/lu/anaconda3/envs/renv/lib/python3.8/site-packages/rpy2/ipython/rmagic.py in eval(self, code)
    266             try:
    267                 # Need the newline in case the last line in code is a comment.
--> 268                 value, visible = ro.r("withVisible({%s\n})" % code)
    269             except (ri.embedded.RRuntimeError, ValueError) as exception:
    270                 # Otherwise next return seems to have copy of error.

/data/lu/anaconda3/envs/renv/lib/python3.8/site-packages/rpy2/robjects/__init__.py in __call__(self, string)
    435 
    436     def __call__(self, string):
--> 437         p = rinterface.parse(string)
    438         res = self.eval(p)
    439         return conversion.rpy2py(res)

/data/lu/anaconda3/envs/renv/lib/python3.8/site-packages/rpy2/rinterface_lib/conversion.py in _(*args, **kwargs)
     43 def _cdata_res_to_rinterface(function):
     44     def _(*args, **kwargs):
---> 45         cdata = function(*args, **kwargs)
     46         # TODO: test cdata is of the expected CType
     47         return _cdata_to_rinterface(cdata)

/data/lu/anaconda3/envs/renv/lib/python3.8/site-packages/rpy2/rinterface.py in parse(text, num)
     98     robj = StrSexpVector([text])
     99     with memorymanagement.rmemory() as rmemory:
--> 100         res = _rinterface._parse(robj.__sexp__._cdata, num, rmemory)
    101     return res
    102 

/data/lu/anaconda3/envs/renv/lib/python3.8/site-packages/rpy2/rinterface_lib/_rinterface_capi.py in _parse(cdata, num, rmemory)
    650     # PARSE_EOF
    651     if status[0] != openrlib.rlib.PARSE_OK:
--> 652         raise RParsingError('Parsing status not OK',
    653                             status=PARSING_STATUS(status[0]))
    654     return res

RParsingError: Parsing status not OK - PARSING_STATUS.PARSE_ERROR

**Comment by lu77777777** [comment]
And I tried this:
%%R -i data_mat -i input_groups -o size_factors
size_factors = sizeFactors(computeSumFactors(SingleCellExperiment(list(counts=data_mat)), clusters=input_groups, min.mean=0.1))

it still has error messages:
RParsingError                             Traceback (most recent call last)
<ipython-input-24-ca314453d5d7> in <module>
----> 1 get_ipython().run_cell_magic('R', '-i data_mat -i input_groups -o size_factors', 'size_factors = sizeFactors(computeSumFactors(SingleCellExperiment(list(counts=data_mat)), clusters=input_groups, min.mean=0.1))\nprint lei\n')

/data/lu/anaconda3/envs/renv/lib/python3.8/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2397             with self.builtin_trap:
   2398                 args = (magic_arg_s, cell)
-> 2399                 result = fn(*args, **kwargs)
   2400             return result
   2401 

<decorator-gen-121> in R(self, line, cell, local_ns)

/data/lu/anaconda3/envs/renv/lib/python3.8/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/data/lu/anaconda3/envs/renv/lib/python3.8/site-packages/rpy2/ipython/rmagic.py in R(self, line, cell, local_ns)
    761                     return_output = False
    762             else:
--> 763                 text_result, result, visible = self.eval(code)
    764                 text_output += text_result
    765                 if visible:

/data/lu/anaconda3/envs/renv/lib/python3.8/site-packages/rpy2/ipython/rmagic.py in eval(self, code)
    266             try:
    267                 # Need the newline in case the last line in code is a comment.
--> 268                 value, visible = ro.r("withVisible({%s\n})" % code)
    269             except (ri.embedded.RRuntimeError, ValueError) as exception:
    270                 # Otherwise next return seems to have copy of error.

/data/lu/anaconda3/envs/renv/lib/python3.8/site-packages/rpy2/robjects/__init__.py in __call__(self, string)
    435 
    436     def __call__(self, string):
--> 437         p = rinterface.parse(string)
    438         res = self.eval(p)
    439         return conversion.rpy2py(res)

/data/lu/anaconda3/envs/renv/lib/python3.8/site-packages/rpy2/rinterface_lib/conversion.py in _(*args, **kwargs)
     43 def _cdata_res_to_rinterface(function):
     44     def _(*args, **kwargs):
---> 45         cdata = function(*args, **kwargs)
     46         # TODO: test cdata is of the expected CType
     47         return _cdata_to_rinterface(cdata)

/data/lu/anaconda3/envs/renv/lib/python3.8/site-packages/rpy2/rinterface.py in parse(text, num)
     98     robj = StrSexpVector([text])
     99     with memorymanagement.rmemory() as rmemory:
--> 100         res = _rinterface._parse(robj.__sexp__._cdata, num, rmemory)
    101     return res
    102 

/data/lu/anaconda3/envs/renv/lib/python3.8/site-packages/rpy2/rinterface_lib/_rinterface_capi.py in _parse(cdata, num, rmemory)
    650     # PARSE_EOF
    651     if status[0] != openrlib.rlib.PARSE_OK:
--> 652         raise RParsingError('Parsing status not OK',
    653                             status=PARSING_STATUS(status[0]))
    654     return res

RParsingError: Parsing status not OK - PARSING_STATUS.PARSE_ERROR

**Comment by LuckyMD** [comment]
Are you running this in the jupyter notebook? And what is `\nprint lei\n` in the end of the command?

**Comment by lu77777777** [comment]
Hi,
I run this program in jupyter notebook. 
please ignore the \nprint lei\n since I want to determine these sentences finished running
