### ISSUE TITLE
(Report a problem) Cannot reindex from a duplicate axis 

### ISSUE THREAD

**Issue by Teerapon789** [theislab/single-cell-tutorial#67]
I encountered the problem when I used your data and performed your original codes. 
[scRNA-seq Analysis (Practice).md](https://github.com/theislab/single-cell-tutorial/files/6416362/scRNA-seq.Analysis.Practice.md)

**Comment by LuckyMD** [comment]
Could you please copy the error traceback here (see for example how issues are reported in #41). Also check previously posted issues, such as #57 which might give you a hint at where the issue is coming from and how to fix it.

**Comment by Teerapon789** [comment]
Dear Dr Malte Luecken,
  I already fixed the problem now. Thank you so much

  Kind Regards,
 Teerapon
________________________________

**Comment by LuckyMD** [comment]
That's good to hear! Do you want to post how you fixed it here, so that others who encounter the same issue can see how to fix their issue as well?

**Comment by JakeLehle** [comment]
I had this issue as well and using the advice from #57 fixed it by adding adata.var_names_make_unique() to the bottom of cell 5 fixed it for me. This issue can probably be closed now.

**Comment by goodez** [comment]
I ran into the same issue and added `adata.var_names_make_unique()` at the end of cell 5. There's another past issue on this as well. Why not update it? I was using the latest repo and docker image.

**Comment by LuckyMD** [comment]
There is a new notebook in a PR that i have been meaning to check, but haven't found the time yet unfortunately. This is just part of a larger effort.

**Comment by xiaoshichang** [comment]
在 genes文件里面有一些重复值，例如mm10_Flg。但是这些值需要用来做index，所以要在cell5的最后加上adata.var_names_make_unique()，让anndata自动加上后缀区分这些相同的值，才能进行后面的数据合并。

**Comment by LuckyMD** [comment]
Sorry, I'm afraid I don't speak mandarin.
