### ISSUE TITLE
Cannot open jupyter lab in docker container

### ISSUE THREAD

**Issue by dong7422** [theislab/single-cell-tutorial#68]
Hi, I am new to all this and have a very simple question. I am using windows 10 and am running the latest docker image. However when I opened the CLI and typed in jl, it said jl: not found. If I do jupyter lab --allow-root, I can get a url but when I try to open it in browser it says localhost refused to connect.

**Comment by LuckyMD** [comment]
Hey! When you start the docker image you may need to pass ports to be able to start a browser from outside the docker container. That's usually done by setting the `-p` flag in your `docker run` command. Check out the documentation [here](https://docs.docker.com/engine/reference/commandline/run/). I'm sure they have examples of this somewhere as well.
