### ISSUE TITLE
Error in dataloader

### ISSUE THREAD

**Issue by wiedemer** [theislab/single-cell-tutorial#71]
When trying to run the [latest notebook ](https://github.com/theislab/single-cell-tutorial/blob/master/latest_notebook/Case-study_Mouse-intestinal-epithelium_1906.ipynb)I am getting the following error in cell 6:
![Error Part 1](https://user-images.githubusercontent.com/76942427/123445436-28da9d00-d5d8-11eb-80cf-6fd50909d78f.png)
![Error Part 2](https://user-images.githubusercontent.com/76942427/123445442-2aa46080-d5d8-11eb-9a9c-e9d0decfe233.png)

I am running the notebook from within the docker image. Specs:
![Specs 1](https://user-images.githubusercontent.com/76942427/123446133-dbaafb00-d5d8-11eb-97f8-db221ff80c0c.png)
![Specs 2](https://user-images.githubusercontent.com/76942427/123446137-dc439180-d5d8-11eb-8ae0-15de883ef2f7.png)

I have tried:

- Restarting the kernel

- Deleting and reloading the data folder

**Comment by LuckyMD** [comment]
Hi @wiedemer,

Thanks for reporting your issue here. I think the issue might be that I'm very slow at putting out the latest version of the notebook. The docker image you are running is already using newer versions of packages that match an updated version of the tutorial I haven't checked properly yet. Could you try to see if it works with the older version of the docker image with tag `200402`?

**Comment by wiedemer** [comment]
Thanks @LuckyMD! That did something. Now my Kernel dies at the end of that cell every time:
![Kernel has died.](https://user-images.githubusercontent.com/76942427/123454923-5f68e580-d5e1-11eb-9927-d439276d4b6a.png)

**Comment by LuckyMD** [comment]
The kernel dying might have more to do with the available memory you have, rather than the code. It looks like your kernel dies as soon as you are loading the datasets.

**Comment by wiedemer** [comment]
Thank you again. I hope I got it from here. I'll close this issue by mentioning that the yml file route leads to the ame issue for me. So the turorial is impossible to get running using the info available in the readme right now as far as I can tell.

**Comment by LuckyMD** [comment]
Which issue does the yml file route lead to? To your kernel dying? Or to the reindex issue?

**Comment by wiedemer** [comment]
The former. Exact same line exact same issue. Simply running the commands from the readme leads to an error adressed in #69. Here is the specs from my conda env after manually changing some versions to get the imports to run:
![Conda specs 1](https://user-images.githubusercontent.com/76942427/123619977-062fca80-d80a-11eb-8c8d-34422880abec.png)
![Conda specs 2](https://user-images.githubusercontent.com/76942427/123619986-08922480-d80a-11eb-9c51-a4a44a16de08.png)

Error message is the same.

**Comment by LuckyMD** [comment]
Sorry about that. I'm not sure how to address the issue of your kernel dying. That's quite difficult to assess from afar.
