### ISSUE TITLE
Package versions in .yml file

### ISSUE THREAD

**Issue by lefterov** [theislab/single-cell-tutorial#74]
It is rather a question, not an issue:

in the .yml file some of the packages are listed with older than most recent versions: 

- python>=3.5, <3.7
- cmake>=3.9, <3.11

the most recent and installed are:
                -python=3.9.7
                -cmake=3.21.2

there should not be a problem, right?

nice day,

Iliya

**Comment by LuckyMD** [comment]
Hey!

I can't imagine there would be a problem with cmake updates. For python, I'm not sure... but I don't think there should be backwards compatibility issues there either. Sorry I can't give you a more detailed answer.

**Comment by lefterov** [comment]
Absolute and excellent answer.

Have a great day!


-I.

Iliya Lefterov
Professor, School of Public Health
University of Pittsburgh

+1 412 449 9195 (mobile, USA)
***@***.***

From: MalteDLuecken ***@***.***>
Date: Tuesday, September 7, 2021 at 6:10 AM
To: theislab/single-cell-tutorial ***@***.***>
Cc: Lefterov, Iliya ***@***.***>, Author ***@***.***>
Subject: Re: [theislab/single-cell-tutorial] Package versions in .yml file (#74)

Hey!

I can't imagine there would be a problem with cmake updates. For python, I'm not sure... but I don't think there should be backwards compatibility issues there either. Sorry I can't give you a more detailed answer.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftheislab%2Fsingle-cell-tutorial%2Fissues%2F74%23issuecomment-914176782&data=04%7C01%7Ciliyal%40pitt.edu%7C0ac6deab8bee4374699908d971e7c25d%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637666062480791129%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MANVzB3aM37eR7G0v2AVoOWVEAMJb7pL1YDl%2FpEvaT0%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAANSETRM4YPCWQ7NUCZ4SNTUAXQKLANCNFSM5DSAHHZQ&data=04%7C01%7Ciliyal%40pitt.edu%7C0ac6deab8bee4374699908d971e7c25d%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637666062480791129%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Gjs8Mbxxb1%2BNeDrKTKx1fZhXuUClaO1zGlnzGTJr3MA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ciliyal%40pitt.edu%7C0ac6deab8bee4374699908d971e7c25d%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637666062480801122%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kiL4yez4gkkwgOjHggHKK%2B1fjRt42bFOL7QNZzAzQ2Y%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ciliyal%40pitt.edu%7C0ac6deab8bee4374699908d971e7c25d%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637666062480811118%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9YqpTfxampfeif2AjgqE%2BBwzm3BcQ8UUc862sEaSaVQ%3D&reserved=0>.

**Comment by lefterov** [comment]
at this time I have no problem with the newest versions. I don't know if it is worth changing the content of the .yml file. for more experienced users, such a question would not have existed.

**Comment by LuckyMD** [comment]
I'm trying to stick to the docker rather than the yaml file for the moment. But could you add this as a comment on the PR #58 ? Then I can try to add it there when i get around to it.

**Comment by lefterov** [comment]
Posted.

Thanks, Malte. What if I permit myself in the near future to send questions directly… 😊?

Nice evening.

-I.

--
Iliya Lefterov, MD, PhD
Professor, Graduate School of Public Health
Department of Environmental  & Occupational Health
University of Pittsburgh, Public Health,
130 De Soto Str., Rm 4134
Pittsburgh, PA 15261

Tel. office: 412 383 6906
        Lab:     412 6248662
        Email:  ***@***.******@***.***>


From: MalteDLuecken ***@***.***>
Date: Wednesday, September 8, 2021 at 12:10 PM
To: theislab/single-cell-tutorial ***@***.***>
Cc: Lefterov, Iliya ***@***.***>, Author ***@***.***>
Subject: Re: [theislab/single-cell-tutorial] Package versions in .yml file (#74)

I'm trying to stick to the docker rather than the yaml file for the moment. But could you add this as a comment on the PR #58<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftheislab%2Fsingle-cell-tutorial%2Fpull%2F58&data=04%7C01%7Ciliyal%40pitt.edu%7C04f4da66208747fa177e08d972e33c2d%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637667142580490401%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xg1NDGZcv883sdoglkIC3ialKX%2FCYqgH1Cndw82%2F0R0%3D&reserved=0> ? Then I can try to add it there when i get around to it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftheislab%2Fsingle-cell-tutorial%2Fissues%2F74%23issuecomment-915374309&data=04%7C01%7Ciliyal%40pitt.edu%7C04f4da66208747fa177e08d972e33c2d%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637667142580500394%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wlXpb1QjwDe4nnYqSOBbPYumJLWjLm%2BDFQ%2FkhYt71i0%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAANSETUQ5BV5733CCF5UMBDUA6DI3ANCNFSM5DSAHHZQ&data=04%7C01%7Ciliyal%40pitt.edu%7C04f4da66208747fa177e08d972e33c2d%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637667142580500394%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9yp2qK1H1kXUIDzqot9O%2FsDSIaqf1DHgfKuAHEkGPSA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ciliyal%40pitt.edu%7C04f4da66208747fa177e08d972e33c2d%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637667142580510386%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZiZfRb0cMYjuUtrvcSeMHW6FhlTMNZ5ezzfh6mmKLTQ%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ciliyal%40pitt.edu%7C04f4da66208747fa177e08d972e33c2d%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637667142580510386%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WSbp4thjVVNDHmmeGYyYrsfFBwsvYOcwlRzBG%2FzmTPY%3D&reserved=0>.

**Comment by LuckyMD** [comment]
Thanks. I'm usually quite responsive on github as well ;).

**Comment by lefterov** [comment]
I am working on Scanpy Tutorials. No problems there until now.

I try to reproduce your Notebook, only to make sure that it works in the elegant way you described and we are fascinated… (in our latest Nature paper we used Seurat…)

The problem that I hit with your Case-study… were the R libraries. The way I found import rpy2 and then importr. thus in Jupyter Notebook I don’t have to specify .libPaths. all R libraries are loaded automatically with

importr('scran')
…and everything else…

NOW: if I nbconvert the .ipynb to executable python script, and run it

Ipython single-cell-trial0907.py

the R libraries are inaccessible. My guess is that I must create a ./library directory and copy the R libraries necessary for being able to load the R libraries and execute the python script on the command line…


Malte, I am not a python guy, and I am not suggesting changing the notebook… (I am too small for that); it is just a comment, and please (if you want) edit this if you are going to post to #54

-I.
--
Iliya Lefterov
Professor, School of Public Health
University of Pittsburgh

+1 412 449 9195 (mobile, USA)
***@***.***

From: MalteDLuecken ***@***.***>
Date: Wednesday, September 8, 2021 at 12:49 PM
To: theislab/single-cell-tutorial ***@***.***>
Cc: Lefterov, Iliya ***@***.***>, Author ***@***.***>
Subject: Re: [theislab/single-cell-tutorial] Package versions in .yml file (#74)

Thanks. I'm usually quite responsive on github as well ;).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftheislab%2Fsingle-cell-tutorial%2Fissues%2F74%23issuecomment-915402018&data=04%7C01%7Ciliyal%40pitt.edu%7C990fd2d95f9e4747abbb08d972e8a49e%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637667165784798108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CtUu2swMWm9sUpInOIvYzeNy%2BLfrM6wfs%2BSItNxNlNU%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAANSETXSKHF6F2RDBSSET3TUA6H2BANCNFSM5DSAHHZQ&data=04%7C01%7Ciliyal%40pitt.edu%7C990fd2d95f9e4747abbb08d972e8a49e%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637667165784808103%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=A30ZdqMyxHlzGUzg7JuswNRqYFF84B6ej3uHPpDLGPg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ciliyal%40pitt.edu%7C990fd2d95f9e4747abbb08d972e8a49e%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637667165784808103%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jfoNHpPxgEN%2FXUxuuwWIo1CNhDDttUzapcw3ebQH3os%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ciliyal%40pitt.edu%7C990fd2d95f9e4747abbb08d972e8a49e%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637667165784818094%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MNZLlocXcR%2Ffmp5vRt5rWtcCUXX0wUtvuKrl1DNAixQ%3D&reserved=0>.

**Comment by dturaev** [comment]
Here is some additional information:
- with the original yml file, conda was stuck at "Solving environment" for many hours, so I aborted
- removing the version restrictions from `python>=3.5, <3.7` and `cmake>=3.9, <3.11` to `python` and `cmake` allowed for solving the environment, however the installation (creating the Makefile for fa2) failed with the error message was "CMake Error: Unknown argument --" (cmake 3.21.2), which seems to be related to https://gitlab.kitware.com/cmake/cmake/-/issues/22060
- after adding `cmake <=3.19`, the installation (building the wheel for fa2) failed with error messages like `error: 'PyTypeObject' {aka 'struct _typeobject'} has no member named 'tp_print'`, which seems to be related to changes in Python 3.9
- after adding `python=3.8`, the installation completed successfully. So, the versions that worked for me were `python=3.8` and `cmake <=3.19`

**Comment by lefterov** [comment]
👍

Beginning Monday, I am moving full speed again… means I will let you know how it works and, definitely – will have more questions… :-)

Cheers, and nice weekend.

-I.
--
Iliya Lefterov
Professor, School of Public Health
University of Pittsburgh

+1 412 449 9195 (mobile, USA)
***@***.***

From: DT ***@***.***>
Date: Saturday, September 18, 2021 at 4:57 PM
To: theislab/single-cell-tutorial ***@***.***>
Cc: Lefterov, Iliya ***@***.***>, Author ***@***.***>
Subject: Re: [theislab/single-cell-tutorial] Package versions in .yml file (#74)

Here is some additional information:

  *   with the original yml file, conda was stuck at "Solving environment" for many hours, so I aborted
  *   removing the version restrictions from python>=3.5, <3.7 and cmake>=3.9, <3.11 to python and cmake allowed for solving the environment, however the installation (creating the Makefile for fa2) failed with the error message was "CMake Error: Unknown argument --" (cmake 3.21.2), which seems to be related to https://gitlab.kitware.com/cmake/cmake/-/issues/22060<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgitlab.kitware.com%2Fcmake%2Fcmake%2F-%2Fissues%2F22060&data=04%7C01%7Ciliyal%40pitt.edu%7Cb52cbcb3bd204420de1208d97ae6e580%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637675954376428574%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=asmTtaEmciw0C7QCtGBocfL99447lbiSjcTAw4Mfu5g%3D&reserved=0>
  *   after adding cmake <=3.19, the installation (building the wheel for fa2) failed with the error message error: 'PyTypeObject' {aka 'struct _typeobject'} has no member named 'tp_print', which seems to be related to the changes in Python 3.9
  *   after adding python=3.8, the installation completed successfully. So, the versions that worked for me were python=3.8 and cmake <=3.19

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftheislab%2Fsingle-cell-tutorial%2Fissues%2F74%23issuecomment-922372714&data=04%7C01%7Ciliyal%40pitt.edu%7Cb52cbcb3bd204420de1208d97ae6e580%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637675954376428574%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jW6ZSjpeO8aFBUs2cei08fpa4PidtXmmfxmblxUqtRw%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAANSETUCLXDK46DELBKIL3DUCT4KXANCNFSM5DSAHHZQ&data=04%7C01%7Ciliyal%40pitt.edu%7Cb52cbcb3bd204420de1208d97ae6e580%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637675954376438569%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pzFQXxi7aQReGrAIGFohkrPXmnJ%2Fkq01DodRzCypues%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ciliyal%40pitt.edu%7Cb52cbcb3bd204420de1208d97ae6e580%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637675954376438569%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oaBJ%2BjQ5ogI67JwhuN2qQXTBaZIZMI1AGx0A6atjtSI%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ciliyal%40pitt.edu%7Cb52cbcb3bd204420de1208d97ae6e580%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637675954376448562%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=l819mXffzdH4l%2BBRwvhtr8rXwKi6Jlv3CDwchlpLDWk%3D&reserved=0>.

**Comment by LuckyMD** [comment]
@dturaev Thanks so much for that! This is really useful!

**Comment by lefterov** [comment]
@LuckyMD: We have finally moved to diffxpy and are trying to move faster...

quick question: to compare two groups (each comprised of 2 biological replicates), is it sufficient to supply the h5ad files written after we ranked the genes using Wilcoxon method?

Thanks in advance.
