### ISSUE TITLE
Batch correction runtime warning: Divide by zero

### ISSUE THREAD

**Issue by dturaev** [theislab/single-cell-tutorial#79]
Hi, thanks for this great resource! When reproducing the notebook using the example data, at "2.3 Batch correction" I'm getting the following output:

```python
# ComBat batch correction
sc.pp.combat(adata, key='sample')
```
```
Standardizing Data across genes.

Found 6 batches

Found 0 numerical variables:
	

Fitting L/S model and finding priors

Finding parametric adjustments

/apps/anaconda3/envs/sc-tutorial/lib/python3.8/site-packages/scanpy/preprocessing/_combat.py:340: RuntimeWarning: divide by zero encountered in true_divide
  (abs(g_new - g_old) / g_old).max(), (abs(d_new - d_old) / d_old).max()

Adjusting data
```

Subsequent plots and results start to differ from the ones in the reference notebook. E.g., I'm seeing:

```python
adata.obs['louvain_r0.5'].value_counts()
```

```
0    4614
1    2666
2    1787
3    1365
4     799
5     686
6     283
7     257
Name: louvain_r0.5, dtype: int64
```

instead of the expected output

```
0    2361
1    2246
2    2099
3    1804
4    1479
5    1309
6     646
7     268
8     245
Name: louvain_r0.5, dtype: int64
``` 

I appreciate any suggestions on this. Thank you.

**Comment by LuckyMD** [comment]
Hi!
There is inherent stochasticity in the notebook at several stages (louvain, PCA, etc). So some results might not be reproducible 100%. I would hope however that if you run your analysis in the docker container provided this should not be an issue. Have you tried this? Could you post the UMAP comparison here to at least give some idea of the difference in the runs?

As for the divide by zero, is this run on the tutorial data? If it's only a warning, at least it's still running... but I'm not sure that the results would be exactly the same... Have you run all the steps before (like removing 0 count genes, etc.)?

**Comment by dturaev** [comment]
Thanks, and sorry for the late reply! Yes, I'm trying to reproduce the tutorial data, and ran all previous steps from the notebook. I haven't tried the Docker container. Below is the output of `sc.pl.umap(adata, color='n_counts')`:  
![tmp](https://user-images.githubusercontent.com/8933948/167201202-f8336fe0-b809-426a-bff1-0d3b470bec40.png)

**Comment by LuckyMD** [comment]
I think the stochasticity above is expected. So I wouldn't worry about this.

**Comment by dturaev** [comment]
I see, thank you. I'm still not sure about the "divide by zero encountered in true_divide" runtime warning, so if someone else encounters this, please comment.

**Comment by LuckyMD** [comment]
This should have to do with genes that are not expressed in a particular batch. So a more rigorous gene filtering should remove those I think.

**Comment by dturaev** [comment]
Thanks, I'll try this!
