### ISSUE TITLE
numpy.core._exceptions.MemoryError: Unable to allocate 926. GiB for an array with shape (6794880, 36601) and data type float32

### ISSUE THREAD

**Issue by DUAN-GAO** [theislab/single-cell-tutorial#85]
hi, all, I find when my reading from a big 10x matrix file, it gives me below error:
numpy.core._exceptions.MemoryError: Unable to allocate 926. GiB for an array with shape (6794880, 36601) and data type float32

**Comment by Zethson** [comment]
This is not an issue with this tutorial, but rather your environment not having enough RAM for this big dataset.
