### ISSUE TITLE
clustering resolutions--how to tune

### ISSUE THREAD

**Issue by DUAN-GAO** [theislab/single-cell-tutorial#86]
Hello guys, 
Investigating several resolutions allows us to select a clustering that appears to capture the main clusters in the visualization.
I find in the notebook no comparison between different resolutions, given the resolution is a parameter, I think we should tune it, but the author did not do it, would like to know the reasons.
Many thanks.

**Comment by LuckyMD** [comment]
Hey @Iweirdo,
That's a good point. The notebook just goes through a use case as a solution, but doesn't show the difficulties analysts might have to go through at different stages. Typically there is of course a back and forth between different clustering resolutions and then subclustering of the individual clusters, etc. The notebook does show the subclustering process, but not so much the first decision making step.

Do you have any particular questions on this? In general I think the first choice of clustering resolution is mostly a choice that determines how much or how little subclustering must be done. If you choose a low resolution then you may have to do more subclustering, with a high resolution you may want to merge finer clusters. This is usually done based on marker genes derived from literature or the data itself. Is this what you were looking for?

**Comment by DUAN-GAO** [comment]
@LuckyMD
Many thanks Mr Malte, you are always helpful to me, you may leave a Etherum Classic address, wanna buy a cup of coffee for you. ☕

**Comment by Iweirdo** [comment]
@LuckyMD
Many thanks Mr Malte, you are always helpful to me, you may leave a Etherum Classic address, wanna buy a cup of coffee for you. ☕

**Comment by LuckyMD** [comment]
Haha, that's kind, but I'm happy to help. No worries.
