### ISSUE TITLE
combine clusters after clustering

### ISSUE THREAD

**Issue by DUAN-GAO** [theislab/single-cell-tutorial#87]
Dear author,
After leiden clustering, I got like 10 clusters, next I do marker gene overlaps that gives me a list like ['Natural killer T (NKT) cell', 'Mitotic arrest phase fetal germ cell', 'Microglial cell', 'Natural killer T (NKT) cell', 'Natural killer T (NKT) cell', 'Natural killer T (NKT) cell', 'Natural killer T (NKT) cell', 'Sertoli cell', 'Natural killer T (NKT) cell', 'Natural killer T (NKT) cell'].
It contains duplicates, when I try adata.rename_categories using the list above to rename the clusters, it tells me ValueError: Categorical categories must be unique.
Could you help, many thanks.

**Comment by LuckyMD** [comment]
Hi!
If you have multiple clusters that have the same identity, you first need to create a new annotation with the merged cluster IDs. Something like this:

```
merged_clusters = ['1' if clust in ['1', '2'] else ['3'] if clust in ['3', '4'] else clust for clust in adata.obs['leiden_clusters']]
adata.obs['leiden_clusters_merged'] = merged_clusters
adata.obs['leiden_clusters_merged'] = adata.obs['leiden_clusters_merged'].astype("category")
```

You can also overwrite the `'leiden_clusters'` column if you want ofc.
