### ISSUE TITLE
Use scanpy combat implementation

### ISSUE THREAD

**Issue by ld2113** [theislab/single-cell-tutorial#9]
I just saw that combat is now included in scanpy as of version 1.4

batch correction can therefore be performed with the oneliner: `sc.pp.combat(adata, key='sample')`

this could be included in the updated version of the notebook

this should save people an extra step as they no longer will have to download the combat code from marens github.

**Comment by LuckyMD** [comment]
Hi,

We're working on an updated version of the script, which will include the scanpy combat implementation. It should be uploaded in a week or so.

Other updates will include a nicer move between r and python with an rpy2 dev version, and some more functions which we're looking to integrate into scanpy.
