### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../Macosko_cell_cycle_genes.txt'

### ISSUE THREAD

**Issue by skr3178** [theislab/single-cell-tutorial#92]
cc_genes_file = '../Macosko_cell_cycle_genes.txt'

cc_genes = pd.read_table(cc_genes_file, delimiter='\t')

**Comment by LuckyMD** [comment]
Hi @skr3178,

The file you're looking for is in the main repo.. You should have it if you downloaded the repo in full.

**Comment by skr3178** [comment]
@LuckyMD Thank you for helping out.
