### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by skr3178** [theislab/single-cell-tutorial#93]
There is a problem with the number of clusters that are being generated. I have 8 clusters being generated.

Here is the file link  for this:
https://drive.google.com/file/d/1HX-LpWuvZJeDu8cvLhIyLQ_ncr0Z9-nA/view?usp=sharing

`
sc.pl.rank_genes_groups(adata, key='rank_genes_r0.5', groups=['0','1','2'], fontsize=12)
sc.pl.rank_genes_groups(adata, key='rank_genes_r0.5', groups=['3','4','5'], fontsize=12)
sc.pl.rank_genes_groups(adata, key='rank_genes_r0.5', groups=['6', '7', '8'], fontsize=12)`

**_*Output Error*_ **

`

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-101-3ee6b5f721bc> in <module>
      2 sc.pl.rank_genes_groups(adata, key='rank_genes_r0.5', groups=['0','1','2'], fontsize=12)
      3 sc.pl.rank_genes_groups(adata, key='rank_genes_r0.5', groups=['3','4','5'], fontsize=12)
----> 4 sc.pl.rank_genes_groups(adata, key='rank_genes_r0.5', groups=['6', '7', '8'], fontsize=12)

/opt/python/lib/python3.8/site-packages/scanpy/plotting/_tools/__init__.py in rank_genes_groups(adata, groups, n_genes, gene_symbols, key, fontsize, ncols, sharey, show, save, ax, **kwds)
    287     ymax = -np.Inf
    288     for count, group_name in enumerate(group_names):
--> 289         gene_names = adata.uns[key]['names'][group_name][:n_genes]
    290         scores = adata.uns[key]['scores'][group_name][:n_genes]
    291 

/opt/python/lib/python3.8/site-packages/numpy/core/records.py in __getitem__(self, indx)
    515 
    516     def __getitem__(self, indx):
--> 517         obj = super(recarray, self).__getitem__(indx)
    518 
    519         # copy behavior of getattr, except that here

ValueError: no field of name 8
`

Package List installed:

Package                           Version
--------------------------------- ------------
absl-py                           0.11.0
aniso8601                         8.1.0
anndata                           0.7.5
anndata2ri                        1.0.6
annoy                             1.17.0
anyio                             2.0.2
argon2-cffi                       20.1.0
astunparse                        1.6.3
async-generator                   1.10
attrs                             20.3.0
Babel                             2.9.0
backcall                          0.2.0
bamnostic                         1.1.4
batchglm                          0.7.4
bleach                            3.2.1
boto3                             1.16.54
botocore                          1.19.54
Brotli                            1.0.9
cachetools                        4.2.0
cellrank                          1.1.0
cellxgene                         0.16.6
certifi                           2020.12.5
cffi                              1.14.4
chardet                           4.0.0
click                             7.1.2
cloudpickle                       1.6.0
cmake                             3.18.4.post1
cycler                            0.10.0
Cython                            0.29.21
dask                              2020.12.0
decorator                         4.4.2
defusedxml                        0.6.0
diffxpy                           0.7.4
dm-tree                           0.1.5
docrep                            0.3.1
entrypoints                       0.3
episcanpy                         0.3.0
fa2                               0.3.5
fastobo                           0.9.3
Flask                             1.1.2
Flask-Compress                    1.8.0
Flask-Cors                        3.0.10
Flask-RESTful                     0.3.8
flask-server-timing               0.1.2
flask-talisman                    0.7.0
flatbuffers                       1.12
flatten-dict                      0.3.0
fsspec                            0.7.4
future                            0.18.2
future-fstrings                   1.2.0
gast                              0.3.3
get-version                       2.1
google-auth                       1.24.0
google-auth-oauthlib              0.4.2
google-pasta                      0.2.0
gprofiler-official                1.0.0
grpcio                            1.32.0
gunicorn                          20.0.4
h5py                              2.10.0
idna                              2.10
imageio                           2.9.0
ipykernel                         5.4.3
ipython                           7.19.0
ipython-genutils                  0.2.0
ipywidgets                        7.6.3
itsdangerous                      1.1.0
jedi                              0.18.0
Jinja2                            2.11.2
jmespath                          0.10.0
joblib                            1.0.0
json5                             0.9.5
jsonschema                        3.2.0
jupyter-client                    6.1.11
jupyter-contrib-core              0.3.3
jupyter-contrib-nbextensions      0.5.1
jupyter-core                      4.7.0
jupyter-highlight-selected-word   0.2.0
jupyter-latex-envs                1.4.6
jupyter-nbextensions-configurator 0.4.1
jupyter-server                    1.2.1
jupyterlab                        3.0.4
jupyterlab-pygments               0.1.2
jupyterlab-server                 2.1.2
jupyterlab-widgets                1.0.0
Keras-Preprocessing               1.1.2
kiwisolver                        1.3.1
legacy-api-wrap                   1.2
leidenalg                         0.8.3
llvmlite                          0.35.0
loompy                            3.0.6
louvain                           0.7.0
lxml                              4.6.2
Markdown                          3.3.3
MarkupSafe                        1.1.1
matplotlib                        3.3.3
mistune                           0.8.4
mpi4py                            3.0.3
MulticoreTSNE                     0.1
natsort                           7.1.0
nbclassic                         0.2.6
nbclient                          0.5.1
nbconvert                         6.0.7
nbformat                          5.1.1
nest-asyncio                      1.4.3
networkx                          2.5
notebook                          6.2.0
numba                             0.52.0
numexpr                           2.7.2
numpy                             1.19.5
numpy-groupies                    0.9.13
oauthlib                          3.1.0
opt-einsum                        3.3.0
packaging                         20.8
pandas                            1.2.0
pandocfilters                     1.4.3
parso                             0.8.1
pathlib2                          2.3.5
patsy                             0.5.1
petsc                             3.14.3
petsc4py                          3.14.1
pexpect                           4.8.0
pickleshare                       0.7.5
Pillow                            8.1.0
pip                               20.3.3
progressbar2                      3.53.1
prometheus-client                 0.9.0
prompt-toolkit                    3.0.10
protobuf                          3.14.0
ptyprocess                        0.7.0
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
pycparser                         2.20
pygam                             0.8.0
Pygments                          2.7.4
pyparsing                         2.4.7
pyrsistent                        0.17.3
pysam                             0.16.0.1
python-dateutil                   2.8.1
python-igraph                     0.8.3
python-utils                      2.4.0
pytz                              2020.5
PyWavelets                        1.1.1
PyYAML                            5.3.1
pyzmq                             21.0.0
requests                          2.25.1
requests-oauthlib                 1.3.0
rpy2                              3.4.2
rsa                               4.7
s3fs                              0.4.2
s3transfer                        0.3.4
scanpy                            1.6.1
scikit-image                      0.18.1
scikit-learn                      0.24.0
scipy                             1.6.0
scrublet                          0.2.3
scvelo                            0.2.2
seaborn                           0.11.1
Send2Trash                        1.5.0
setuptools                        51.1.2
setuptools-scm                    5.0.1
sinfo                             0.3.1
six                               1.15.0
slepc                             3.14.0
slepc4py                          3.14.0
sniffio                           1.2.0
sparse                            0.11.2
SQLAlchemy                        1.3.22
statsmodels                       0.12.1
stdlib-list                       0.8.0
tables                            3.6.1
tbb                               2021.1.1
tensorboard                       2.4.0
tensorboard-plugin-wit            1.7.0
tensorflow                        2.4.0
tensorflow-estimator              2.4.0
tensorflow-probability            0.12.1
termcolor                         1.1.0
terminado                         0.9.2
testpath                          0.4.4
texttable                         1.6.3
threadpoolctl                     2.1.0
tifffile                          2021.1.11
tiledb                            0.7.5
toolz                             0.11.1
tornado                           6.1
tqdm                              4.56.0
traitlets                         5.0.5
typing-extensions                 3.7.4.3
tzlocal                           2.1
umap-learn                        0.4.6
urllib3                           1.26.2
vendorize                         0.2.1
wcwidth                           0.2.5
webencodings                      0.5.1
Werkzeug                          1.0.1
wheel                             0.36.2
widgetsnbextension                3.5.1
wrapt                             1.12.1
xlrd                              2.0.1
XlsxWriter                        1.3.7
WARNING: You are using pip version 20.3.3; however, version 22.0.4 is available.
You should consider upgrading via the '/opt/python/bin/python3.8 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

**Comment by LuckyMD** [comment]
Hi @skr3178,

Please check the documentation for the `sc.pl.rank_genes_groups` function in the scanpy ReadTheDocs [here](https://scanpy.readthedocs.io/en/stable/generated/scanpy.pl.rank_genes_groups.html). The Scanpy ReadTheDocs page is a good place to look up functions to find what might not be working as you expect and give you errors. In the above case, this is a fairly straightforward error: you don't have a cluster called '8' in your clustering output. If you remove the '8' from the `groups=` parameter input, it will work.
