### ISSUE TITLE
Too few Duodenum cells

### ISSUE THREAD

**Issue by Mari123i** [theislab/single-cell-tutorial#94]
RESOLVED

Hello dear Authors,
thank you for that great notebook and corresponding paper! 
I have an question about the counts of duodenum they turned out to be about half the expected count (see screenshot). The only thing I changed was to add: 
_adata.var_names_make_unique()_
since I had issues otherwise when loading data. (There is an issue like that on git also).
How  come that is counts half of the data? I did not modify the dataset.
Thank you!
<img width="552" alt="too few Duo cells" src="https://user-images.githubusercontent.com/104916079/167384759-ef3c13b8-f261-42b8-86ab-39cb1b0bda2c.PNG">
!

THE ISSUE WAS RESOLVED:
I had to just rerun the whole thing again, so that the list with names and sample is reinitialized

**Comment by LuckyMD** [comment]
good that you figured it out :)
