### ISSUE TITLE
Key Error "base" in section "marker genes & annotation"

### ISSUE THREAD

**Issue by Mari123i** [theislab/single-cell-tutorial#97]
Hello Malte,
I get the following issue in the Marker genes section: 
This is my AnnData Object:
<img width="757" alt="andata" src="https://user-images.githubusercontent.com/104916079/169283553-1cd2b180-6f30-41a8-8f04-b54ed6c5d8de.PNG">
And this is the error I get:
<img width="819" alt="Anndata error base" src="https://user-images.githubusercontent.com/104916079/169283568-f3b23ef0-0bb0-4158-a286-d9f29cee5c5e.PNG">
I work with the tutorial dataset in case it is relevant, but had to skip few steps containing R code.

Greetings,
Mariam

Edit:
The adata.uns["log1p"] seems to be empty
![Bild_2022-05-19_134147024](https://user-images.githubusercontent.com/104916079/169285221-3e336d56-7eb0-492c-a139-ee86f7725002.png)

**Comment by LuckyMD** [comment]
Hi @Mari123i,

Did you run `sc.pp.log1p` on the data at some point? Then this slot should exist. Also, which version of scanpy are you using?

**Comment by Mari123i** [comment]
Hello,  
Yes. I use 1.9.1. Its seems to be an error of saving it and loading it again

**Comment by LuckyMD** [comment]
This seems to be a scanpy bug as you can see [here](https://github.com/scverse/scanpy/issues/2181) and [here](https://github.com/scverse/scanpy/issues/2239). The latter issue suggests to just add the line:

`adata.uns['log1p']["base"] = None` after reading again, or downgrading to AnnData<0.8. Either way, this should be fixed soon by the maintenance team.

**Comment by Mari123i** [comment]
It works! Thank you alot!
