### ISSUE TITLE
Can we also use Seurat v3 v4 or liger in scanpy or python?

### ISSUE THREAD

**Issue by melancholy12** [theislab/single-cell-tutorial#98]
The scanpy has MNN, BBKNN and harmony for us to use. Can we also use Seurat v3 v4 or liger in scanpy or python?

**Comment by LuckyMD** [comment]
Hi @melancholy12,

We previously tried to implement a python wrapper around the R functions for Seurat v3 and LIGER in [scIB](https://github.com/theislab/scib). However, we found that they didn't always work exactly the same way as when run in a pure R environment. You can however do this yourself using [`rpy2`](https://github.com/rpy2/rpy2) and [`anndata2ri` ](https://github.com/theislab/anndata2ri).

That would look something like

```
from rpy2 import robjects as ro
import anndata2ri

anndata2ri.activate()

adata = sc.datasets.pbmc68k_reduced()

ro.globalenv["data"] = adata

ro.r('library(Seurat)')
ro.r('seurat_obj <- as.Seurat(adata)')

# Do your R integration in Seurat within ro.r('')
ro.r('...')

output = ro.r('as.SingleCellExperiment(seurat_obj)')
```

By going via SingleCellExperiment objects and `anndata2ri.activate()` you should be able to easily transfer the data between R and python from a python framework.

**Comment by melancholy12** [comment]
> Hi @melancholy12,
> 
> We previously tried to implement a python wrapper around the R functions for Seurat v3 and LIGER in [scIB](www.github.com/theislab/scib). However, we found that they didn't always work exactly the same way as when run in a pure R environment. You can however do this yourself using [`rpy2`](https://github.com/rpy2/rpy2) and [`anndata2ri` ](www.github.com/theislab/anndata2ri).
> 
> That would look something like
> 
> ```
> from rpy2 import robjects as ro
> import anndata2ri
> 
> anndata2ri.activate()
> 
> adata = sc.datasets.pbmc68k_reduced()
> 
> ro.globalenv["data"] = adata
> 
> ro.r('library(Seurat)')
> ro.r('seurat_obj <- as.Seurat(adata)')
> 
> # Do your R integration in Seurat within ro.r('')
> ro.r('...')
> 
> output = ro.r('as.SingleCellExperiment(seurat_obj)')
> ```
> 
> By going via SingleCellExperiment objects and `anndata2ri.activate()` you should be able to easily transfer the data between R and python from a python framework.

Hi LuckMD,
Thanks for your reply. Could we simply run it in python instead of using R language?
Just something like scanpy.external.harmony?
Because we are familiar with scanpy, and not want to change the coding style.

**Comment by LuckyMD** [comment]
Hi @melancholy12,

No, there is currently no python implementation of these methods specifically. You would have to wrap the R function calls with `rpy2` to make this work from python. The syntax would still be quite some R. There are basic implementations of these methods in the scib-pipeline repo [here](https://github.com/theislab/scib-pipeline) though. Maybe that helps to become familiar with how to call them.

**Comment by melancholy12** [comment]
> Hi @melancholy12,
> 
> No, there is currently no python implementation of these methods specifically. You would have to wrap the R function calls with `rpy2` to make this work from python. The syntax would still be quite some R. There are basic implementations of these methods in the scib-pipeline repo [here](www.github.com/theislab/scib-pipeline) though. Maybe that helps to become familiar with how to call them.

There is a new package called pyliger. Here is the link: https://github.com/welch-lab/pyliger
It should be better if it can integrate into scanpy.

**Comment by LuckyMD** [comment]
That sounds like it would be a good feature request for the [scanpy github](https://github.com/scverse/scanpy) :).

**Comment by melancholy12** [comment]
When I try to use the code and anndata2ri package or rpy2, something wrong happened. 
![image](https://user-images.githubusercontent.com/97800939/196550355-2399fdc5-2458-4782-960c-8ce97d74d6ee.png)
@LuckyMD

**Comment by LuckyMD** [comment]
It looks like you haven't installed S4Vectors in the R environment linked to your R kernel on jupyter. This is something to post on the rpy2 or anndata2ri github I think.
