### ISSUE TITLE
sc.tl.rank_genes_groups  and pct1 & pct2 output

### ISSUE THREAD

**Issue by TRakesh0121** [theislab/single-cell-tutorial#99]
p_val avg_logFC pct.1 pct.2 p_val_adj cluster gene
0 3.98493118352729 0.847 0.02 0 NK GNLY
0 2.47629906583393 0.966 0.015 0 NK TYROBP
0 2.20219767335148 0.831 0.017 0 NK FCER1G
0 2.18294112047524 0.797 0.019 0 NK XCL2
0 2.12994775912407 0.746 0.009 0 NK KLRC1
0 1.54408514042894 0.627 0.005 0 NK KLRF1
0 1.27675593461295 0.492 0.003 0 NK SH2D1B
0 0.720425725458553 0.288 0.001 0 NK KIR2DL4

How do we get such table in Scanpy? In Seurat it’s a direct output file.
In ‘sc.tl.rank_genes_groups’ command, I used [pts=True, reference=‘rest’].
Still not getting the output of pct1 and pct2.

Thanks

**Comment by LuckyMD** [comment]
Hi @TRakesh0121,

This is a question for the scanpy github rather than this one. Take a look at the `scanpy.get` functionality.
